const hiragana = {
    'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
    'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
    'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
    'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
    'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
    'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
    'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
    'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
    'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
    'わ': 'wa', 'を': 'wo',
    'ん': 'n',
    'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
    'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
    'だ': 'da', 'ぢ': 'ji', 'づ': 'zu', 'で': 'de', 'ど': 'do',
    'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
    'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
    'きゃ': 'kya', 'きゅ': 'kyu', 'きょ': 'kyo',
    'しゃ': 'sha', 'しゅ': 'shu', 'しょ': 'sho',
    'ちゃ': 'cha', 'ちゅ': 'chu', 'ちょ': 'cho',
    'にゃ': 'nya', 'にゅ': 'nyu', 'にょ': 'nyo',
    'ひゃ': 'hya', 'ひゅ': 'hyu', 'ひょ': 'hyo',
    'みゃ': 'mya', 'みゅ': 'myu', 'みょ': 'myo',
    'りゃ': 'rya', 'りゅ': 'ryu', 'りょ': 'ryo',
    'ぎゃ': 'gya', 'ぎゅ': 'gyu', 'ぎょ': 'gyo',
    'じゃ': 'ja', 'じゅ': 'ju', 'じょ': 'jo',
    'びゃ': 'bya', 'びゅ': 'byu', 'びょ': 'byo',
    'ぴゃ': 'pya', 'ぴゅ': 'pyu', 'ぴょ': 'pyo',
};

const katakana = {
    'ア': 'a', 'イ': 'i', 'ウ': 'u', 'エ': 'e', 'オ': 'o',
    'カ': 'ka', 'キ': 'ki', 'ク': 'ku', 'ケ': 'ke', 'コ': 'ko',
    'サ': 'sa', 'シ': 'shi', 'ス': 'su', 'セ': 'se', 'ソ': 'so',
    'タ': 'ta', 'チ': 'chi', 'ツ': 'tsu', 'テ': 'te', 'ト': 'to',
    'ナ': 'na', 'ニ': 'ni', 'ヌ': 'nu', 'ネ': 'ne', 'ノ': 'no',
    'ハ': 'ha', 'ヒ': 'hi', 'フ': 'fu', 'ヘ': 'he', 'ホ': 'ho',
    'マ': 'ma', 'ミ': 'mi', 'ム': 'mu', 'メ': 'me', 'モ': 'mo',
    'ヤ': 'ya', 'ユ': 'yu', 'ヨ': 'yo',
    'ラ': 'ra', 'リ': 'ri', 'ル': 'ru', 'レ': 're', 'ロ': 'ro',
    'ワ': 'wa', 'ヲ': 'wo',
    'ン': 'n',
    'ガ': 'ga', 'ギ': 'gi', 'グ': 'gu', 'ゲ': 'ge', 'ゴ': 'go',
    'ザ': 'za', 'ジ': 'ji', 'ズ': 'zu', 'ゼ': 'ze', 'ゾ': 'zo',
    'ダ': 'da', 'ヂ': 'ji', 'ヅ': 'zu', 'デ': 'de', 'ド': 'do',
    'バ': 'ba', 'ビ': 'bi', 'ブ': 'bu', 'ベ': 'be', 'ボ': 'bo',
    'パ': 'pa', 'ピ': 'pi', 'プ': 'pu', 'ペ': 'pe', 'ポ': 'po',
    'キャ': 'kya', 'キュ': 'kyu', 'キョ': 'kyo',
    'シャ': 'sha', 'シュ': 'shu', 'ショ': 'sho',
    'チャ': 'cha', 'チュ': 'chu', 'チョ': 'cho',
    'ニャ': 'nya', 'ニュ': 'nyu', 'ニョ': 'nyo',
    'ヒャ': 'hya', 'ヒュ': 'hyu', 'ヒョ': 'hyo',
    'ミャ': 'mya', 'ミュ': 'myu', 'ミョ': 'myo',
    'リャ': 'rya', 'リュ': 'ryu', 'リョ': 'ryo',
    'ギャ': 'gya', 'ギュ': 'gyu', 'ギョ': 'gyo',
    'ジャ': 'ja', 'ジュ': 'ju', 'ジョ': 'jo',
    'ビャ': 'bya', 'ビュ': 'byu', 'ビョ': 'byo',
    'ピャ': 'pya', 'ピュ': 'pyu', 'ピョ': 'pyo',
    'ヴァ': 'va', 'ヴィ': 'vi', 'ヴ': 'vu', 'ヴェ': 've', 'ヴォ': 'vo',
    'ファ': 'fa', 'フィ': 'fi', 'フェ': 'fe', 'フォ': 'fo',
};

const hiraganaKatakanaWords = {
    'にんげん': { romaji: 'ningen', meaning: 'human' },
    'じんるい': { romaji: 'jinrui', meaning: 'humanity' },
    'ひと': { romaji: 'hito', meaning: 'person' },
    'おとこ': { romaji: 'otoko', meaning: 'male' },
    'おとこのひと': { romaji: 'otokonohito', meaning: 'man' },
    'おとこのこ': { romaji: 'otokonoko', meaning: 'boy' },
    'おんな': { romaji: 'onna', meaning: 'female' },
    'おんなのひと': { romaji: 'onnanohito', meaning: 'woman' },
    'おんなのこ': { romaji: 'onnanoko', meaning: 'girl' },
    'あかちゃん': { romaji: 'akachan', meaning: 'baby' },
    'わかもの': { romaji: 'wakamono', meaning: 'youth, young person' },
    'わたし': { romaji: 'watashi', meaning: 'I, myself' },
    'わたくし': { romaji: 'watakushi', meaning: 'I, myself [most formal]' },
    'ぼく': { romaji: 'boku', meaning: 'I, myself [mainly used by males]' },
    'おれ': { romaji: 'ore', meaning: 'I, myself [mainly used by males [informal]]' },
    'あたし': { romaji: 'atashi', meaning: 'I, myself [mainly used by females [softer sounding]]' },
    'しょうじょ': { romaji: 'shoujo', meaning: 'girl' },
    'しょうねん': { romaji: 'shounen', meaning: 'boy' },
    'いしゃ': { romaji: 'isha', meaning: 'doctor' },
    'かんごし': { romaji: 'kangoshi', meaning: 'nurse' },
    'かんごふ': { romaji: 'kangofu', meaning: 'female nurse' },
    'しかい': { romaji: 'shikai', meaning: 'dentist' },
    'はいしゃ': { romaji: 'ha-isha', meaning: 'dentist' },
    'せいじか': { romaji: 'seijika', meaning: 'politician' },
    'べんごし': { romaji: 'bengoshi', meaning: 'lawyer' },
    'しょうぼうし': { romaji: 'shouboushi', meaning: 'firefighter' },
    'けいさつかん': { romaji: 'keisatsukan', meaning: 'police officer' },
    'へいし': { romaji: 'heishi', meaning: 'soldier' },
    'けんちくか': { romaji: 'kenchikuka', meaning: 'architect' },
    'せんせい': { romaji: 'sensei', meaning: 'teacher' },
    'きょうし': { romaji: 'kyoushi', meaning: '(academic) teacher' },
    'かしゅ': { romaji: 'kashu', meaning: 'singer' },
    'エンジニア': { romaji: 'enjinia', meaning: 'engineer' },
    'あし': { romaji: 'ashi', meaning: 'foot, leg' },
    'かかと': { romaji: 'kakato', meaning: 'heel' },
    'すね': { romaji: 'sune', meaning: 'shin' },
    'ひざ': { romaji: 'hiza', meaning: 'knee' },
    'もも': { romaji: 'momo', meaning: 'thigh' },
    'あたま': { romaji: 'atama', meaning: 'head' },
    'かお': { romaji: 'kao', meaning: 'face' },
    'くち': { romaji: 'kuchi', meaning: 'mouth' },
    'くちびる': { romaji: 'kuchibiru', meaning: 'lips' },
    'は': { romaji: 'ha', meaning: 'tooth' },
    'はな': { romaji: 'hana', meaning: 'nose' },
    'め': { romaji: 'me', meaning: 'eye' },
    'ひげ': { romaji: 'hige', meaning: 'moustache, beard' },
    'かみ': { romaji: 'kami', meaning: 'hair' },
    'みみ': { romaji: 'mimi', meaning: 'ear' },
    'おなか': { romaji: 'onaka', meaning: 'stomach' },
    'うで': { romaji: 'ude', meaning: 'arm' },
    'ひじ': { romaji: 'hiji', meaning: 'elbow' },
    'かた': { romaji: 'kata', meaning: 'shoulder' },
    'つめ': { romaji: 'tsume', meaning: 'nail' },
    'て': { romaji: 'te', meaning: 'hand' },
    'てくび': { romaji: 'tekubi', meaning: 'wrist' },
    'てのひら': { romaji: 'te-no-hira', meaning: 'palm of hand' },
    'ゆび': { romaji: 'yubi', meaning: 'finger, toe' },
    'しり': { romaji: 'shiri', meaning: 'buttocks' },
    'かんぞう': { romaji: 'kanzō', meaning: 'liver' },
    'きも': { romaji: 'kimo', meaning: 'liver' },
    'きんにく': { romaji: 'kin'niku', meaning: 'muscle' },
    'くび': { romaji: 'kubi', meaning: 'neck' },
    'こころ': { romaji: 'kokoro', meaning: 'heart [as in feelings]' },
    'こし': { romaji: 'koshi', meaning: 'waist, hip' },
    'しんぞう': { romaji: 'shinzō', meaning: 'heart' },
    'せなか': { romaji: 'senaka', meaning: 'back' },
    'ち': { romaji: 'chi', meaning: 'blood' },
    'にく': { romaji: 'niku', meaning: 'meat' },
    'はだ': { romaji: 'hada', meaning: 'skin' },
    'ひふ': { romaji: 'hifu', meaning: 'skin' },
    'ほね': { romaji: 'hone', meaning: 'bone' },
    'むね': { romaji: 'mune', meaning: 'chest' },
    'かぜ': { romaji: 'kaze', meaning: 'cold [illness]' },
    'げり': { romaji: 'geri', meaning: 'diarrhea' },
    'びょうき': { romaji: 'byōki', meaning: 'illness' },
    'かぞく': { romaji: 'kazoku', meaning: 'family' },
    'りょうしん': { romaji: 'ryoushin', meaning: 'parents' },
    'こども': { romaji: 'kodomo', meaning: 'children, child' },
    'ちち': { romaji: 'chichi', meaning: 'father' },
    'はは': { romaji: 'haha', meaning: 'mother' },
    'つま': { romaji: 'tsuma', meaning: 'wife' },
    'おっと': { romaji: 'otto', meaning: 'husband' },
    'あに': { romaji: 'ani', meaning: 'older brother' },
    'あね': { romaji: 'ane', meaning: 'older sister' },
    'おとうと': { romaji: 'otōto', meaning: 'younger brother' },
    'いもうと': { romaji: 'imōto', meaning: 'younger sister' },
    'きょうだい': { romaji: 'kyōdai', meaning: 'brothers, siblings' },
    'しまい': { romaji: 'shimai', meaning: 'sisters' },
    'そふ': { romaji: 'sofu', meaning: 'grandfather' },
    'そぼ': { romaji: 'sobo', meaning: 'grandmother' },
    'まご': { romaji: 'mago', meaning: 'grandchild' },
    'おじ': { romaji: 'oji', meaning: 'uncle' },
    'おば': { romaji: 'oba', meaning: 'aunt' },
    'いとこ': { romaji: 'itoko', meaning: 'cousin' },
    'めい': { romaji: 'mei', meaning: 'niece' },
    'おい': { romaji: 'oi', meaning: 'nephew' },
    'いきもの': { romaji: 'ikimono', meaning: 'living creatures' },
    'ばけもの': { romaji: 'bakemono', meaning: 'monster' },
    'どうぶつ': { romaji: 'dōbutsu', meaning: 'animal' },
    'チーター': { romaji: 'chītā', meaning: 'cheetah' },
    'いぬ': { romaji: 'inu', meaning: 'dog' },
    'ねこ': { romaji: 'neko', meaning: 'cat' },
    'うし': { romaji: 'ushi', meaning: 'cow' },
    'ぶた': { romaji: 'buta', meaning: 'pig' },
    'うま': { romaji: 'uma', meaning: 'horse' },
    'ひつじ': { romaji: 'hitsuji', meaning: 'sheep' },
    'さる': { romaji: 'saru', meaning: 'monkey' },
    'ねずみ': { romaji: 'nezumi', meaning: 'mouse, rat' },
    'とら': { romaji: 'tora', meaning: 'tiger' },
    'オオカミ': { romaji: 'ōkami', meaning: 'wolf' },
    'うさぎ': { romaji: 'usagi', meaning: 'rabbit' },
    'りゅう': { romaji: 'ryū', meaning: 'dragon' },
    'たつ': { romaji: 'tatsu', meaning: 'dragon' },
    'しか': { romaji: 'shika', meaning: 'deer' },
    'かえる': { romaji: 'kaeru', meaning: 'frog' },
    'がま': { romaji: 'gama', meaning: 'toad' },
    'しし': { romaji: 'shishi', meaning: 'lion' },
    'キリン': { romaji: 'kirin', meaning: 'giraffe' },
    'ぞう': { romaji: 'zō', meaning: 'elephant' },
    'とり': { romaji: 'tori', meaning: 'bird' },
    'にわとり': { romaji: 'niwatori', meaning: 'chicken' },
    'すずめ': { romaji: 'suzume', meaning: 'sparrow' },
    'からす': { romaji: 'karasu', meaning: 'crow, raven' },
    'わし': { romaji: 'washi', meaning: 'eagle' },
    'たか': { romaji: 'taka', meaning: 'hawk, falcon' },
    'さかな': { romaji: 'sakana', meaning: 'fish' },
    'たい': { romaji: 'tai', meaning: 'red snapper' },
    'えび': { romaji: 'ebi', meaning: 'shrimp, lobster' },
    'いわし': { romaji: 'iwashi', meaning: 'sardine' },
    'まぐろ': { romaji: 'maguro', meaning: 'tuna' },
    'かつお': { romaji: 'katsuo', meaning: 'bonito' },
    'さんま': { romaji: 'sanma', meaning: 'pike' },
    'あじ': { romaji: 'aji', meaning: 'horse mackerel' },
    'さば': { romaji: 'saba', meaning: 'mackerel' },
    'イカ': { romaji: 'ika', meaning: 'squid' },
    'タコ': { romaji: 'tako', meaning: 'octopus' },
    'むし': { romaji: 'mushi', meaning: 'insect' },
    'ちょう': { romaji: 'chō', meaning: 'butterfly' },
    'ガ': { romaji: 'ga', meaning: 'moth' },
    'せみ': { romaji: 'semi', meaning: 'cicada' },
    'トンボ': { romaji: 'tonbo', meaning: 'dragonfly' },
    'バッタ': { romaji: 'batta', meaning: 'grasshopper' },
    'クモ': { romaji: 'kumo', meaning: 'spider' },
    'ホタル': { romaji: 'hotaru', meaning: 'firefly' },
    'ハエ': { romaji: 'hae', meaning: 'housefly' },
    'カ': { romaji: 'ka', meaning: 'mosquito, gnat' },
    'ゴキブリ': { romaji: 'gokiburi', meaning: 'cockroach' },
    'カタツムリ': { romaji: 'katatsumuri', meaning: 'snail' },
    'ナメクジ': { romaji: 'namekuji', meaning: 'slug' },
    'ミミズ': { romaji: 'mimizu', meaning: 'earthworm' },
    'かい': { romaji: 'kai', meaning: 'shellfish' },
    'かいがら': { romaji: 'kaigara', meaning: 'shell' },
    'トカゲ': { romaji: 'tokage', meaning: 'lizard' },
    'へび': { romaji: 'hebi', meaning: 'snake' },
    'くま': { romaji: 'kuma', meaning: 'bear' },
    'しょくぶつ': { romaji: 'shokubutsu', meaning: 'plants' },
    'くさ': { romaji: 'kusa', meaning: 'grass' },
    'はな': { romaji: 'hana', meaning: 'flower' },
    'み': { romaji: 'mi', meaning: 'fruit' },
    'き': { romaji: 'ki', meaning: 'tree' },
    'は': { romaji: 'ha', meaning: 'leaf' },
    'はっぱ': { romaji: 'happa', meaning: 'leaf' },
    'ね': { romaji: 'ne', meaning: 'root' },
    'ねっこ': { romaji: 'nekko', meaning: 'root' },
    'くき': { romaji: 'kuki', meaning: 'stem' },
    'きのこ': { romaji: 'kinoko', meaning: 'mushroom' },
    'きく': { romaji: 'kiku', meaning: 'chrysanthemum' },
    'さくら': { romaji: 'sakura', meaning: 'cherry blossom' },
    'まつ': { romaji: 'matsu', meaning: 'pine tree' },
    'うめ': { romaji: 'ume', meaning: 'japanese plum or apricot' },
    'こめ': { romaji: 'kome', meaning: 'uncooked rice' },
    'いね': { romaji: 'ine', meaning: 'rice growing in a field' },
    'むぎ': { romaji: 'mugi', meaning: 'wheat, barley, oats' },
    'やさい': { romaji: 'yasai', meaning: 'vegetable' },
    'くだもの': { romaji: 'kudamono', meaning: 'fruit for eating' },
    'いも': { romaji: 'imo', meaning: 'yam, potato, taro' },
    'まめ': { romaji: 'mame', meaning: 'beans, peas' },
    'だいこん': { romaji: 'daikon', meaning: 'Japanese white radish' },
    'にんじん': { romaji: 'ninjin', meaning: 'carrot' },
    'リンゴ': { romaji: 'ringo', meaning: 'apple' },
    'ミカン': { romaji: 'mikan', meaning: 'mandarin orange' },
    'バナナ': { romaji: 'banana', meaning: 'banana' },
    'かんしょう': { romaji: 'kanshō', meaning: 'banana' },
    'ナシ': { romaji: 'nashi', meaning: 'pear' },
    'クリ': { romaji: 'kuri', meaning: 'chestnut tree' },
    'モモ': { romaji: 'momo', meaning: 'peach' },
    'トマト': { romaji: 'tomato', meaning: 'tomato' },
    'ばんか': { romaji: 'banka', meaning: 'tomato' },
    'スイカ': { romaji: 'suika', meaning: 'watermelon' },
    'たべもの': { romaji: 'tabemono', meaning: 'food' },
    'ちょうしょく': { romaji: 'chōshoku', meaning: 'breakfast' },
    'あさごはん': { romaji: 'asagohan', meaning: 'breakfast' },
    'ひるごはん': { romaji: 'hirugohan', meaning: 'lunch' },
    'ばんごはん': { romaji: 'bangohan', meaning: 'dinner' },
    'ごはん': { romaji: 'gohan', meaning: 'cooked rice or meal' },
    'みそ': { romaji: 'miso', meaning: 'miso' },
    'りょうり': { romaji: 'ryōri', meaning: 'cooking' },
    'サラダ': { romaji: 'sarada', meaning: 'salad' },
    'デザート': { romaji: 'dezāto', meaning: 'dessert' },
    'パン': { romaji: 'pan', meaning: 'bread' },
    'サンドイッチ': { romaji: 'sandoitchi', meaning: 'sandwich' },
    'おやつ': { romaji: 'oyatsu', meaning: 'snack' },
    'かんしょく': { romaji: 'kansoku', meaning: 'snack' },
    'アイスクリーム': { romaji: 'aisukurīmu', meaning: 'ice cream' },
    'たこやき': { romaji: 'takoyaki', meaning: 'octopus dumpling' },
    'のみもの': { romaji: 'nomimono', meaning: 'drink/beverage' },
    'ちゃ': { romaji: 'cha', meaning: 'tea' },
    'おちゃ': { romaji: 'ocha', meaning: 'green tea' },
    'コーヒー': { romaji: 'kōhī', meaning: 'coffee' },
    'ぎゅうにゅう': { romaji: 'gyūnyū', meaning: 'milk' },
    'みず': { romaji: 'mizu', meaning: 'water' },
    'ビール': { romaji: 'bīru', meaning: 'beer' },
    'ワイン': { romaji: 'wain', meaning: 'wine' },
    'さとう': { romaji: 'satō', meaning: 'sugar' },
    'しお': { romaji: 'shio', meaning: 'salt' },
    'しょうゆ': { romaji: 'shōyu', meaning: 'soy sauce' },
    'じかん': { romaji: 'jikan', meaning: 'time' },
    'とき': { romaji: 'toki', meaning: 'time' },
    'じ': { romaji: 'ji', meaning: '~hours' },
    'こよみ': { romaji: 'koyomi', meaning: 'calendar' },
    'カレンダー': { romaji: 'karendā', meaning: 'calendar' },
    'ふん': { romaji: 'fun', meaning: 'minute' },
    'びょう': { romaji: 'byō', meaning: 'second' },
    'ひ': { romaji: 'hi', meaning: 'day' },
    'にち': { romaji: 'nichi', meaning: 'day' },
    'つき': { romaji: 'tsuki', meaning: 'month' },
    'がつ': { romaji: 'gatsu', meaning: 'month' },
    'とし': { romaji: 'toshi', meaning: 'year' },
    'ねん': { romaji: 'nen', meaning: 'year' },
    'きのう': { romaji: 'kinō', meaning: 'yesterday' },
    'さくじつ': { romaji: 'sakujitsu', meaning: 'yesterday' },
    'きょう': { romaji: 'kyō', meaning: 'today' },
    'あした': { romaji: 'ashita', meaning: 'tomorrow' },
    'あす': { romaji: 'asu', meaning: 'tomorrow' },
    'みょうにち': { romaji: 'myōnichi', meaning: 'tomorrow' },
    'あさ': { romaji: 'asa', meaning: 'morning' },
    'ひる': { romaji: 'hiru', meaning: 'afternoon' },
    'ゆうがた': { romaji: 'yūgata', meaning: 'evening' },
    'ばん': { romaji: 'ban', meaning: 'evening' },
    'よる': { romaji: 'yoru', meaning: 'evening, night' },
    'ようび': { romaji: 'yōbi', meaning: '~day' },
    'しゅう': { romaji: 'shū', meaning: 'week' },
    'いっしゅうかん': { romaji: 'isshūkan', meaning: 'one week' },
    'にちようび': { romaji: 'nichi-yōbi', meaning: 'Sunday' },
    'げつようび': { romaji: 'getsu-yōbi', meaning: 'Monday' },
    'かようび': { romaji: 'ka-yōbi', meaning: 'Tuesday' },
    'すいようび': { romaji: 'sui-yōbi', meaning: 'Wednesday' },
    'もくようび': { romaji: 'moku-yōbi', meaning: 'Thursday' },
    'きんようび': { romaji: 'kin-yōbi', meaning: 'Friday' },
    'どようび': { romaji: 'do-yōbi', meaning: 'Saturday' },
    'たいよう': { romaji: 'taiyō', meaning: 'sun' },
    'ほし': { romaji: 'hoshi', meaning: 'star' },
    'てんき': { romaji: 'tenki', meaning: 'weather' },
    'はれ': { romaji: 'hare', meaning: 'clear weather' },
    'あめ': { romaji: 'ame', meaning: 'rain' },
    'くもり': { romaji: 'kumori', meaning: 'cloudy' },
    'ゆき': { romaji: 'yuki', meaning: 'snow' },
    'かぜ': { romaji: 'kaze', meaning: 'wind' },
    'かみなり': { romaji: 'kaminari', meaning: 'thunder, lightning' },
    'たいふう': { romaji: 'taifū', meaning: 'typhoon' },
    'あらし': { romaji: 'arashi', meaning: 'storm' },
    'そら': { romaji: 'sora', meaning: 'sky' },
    'きた': { romaji: 'kita', meaning: 'north' },
    'ひがし': { romaji: 'higashi', meaning: 'east' },
    'みなみ': { romaji: 'minami', meaning: 'south' },
    'にし': { romaji: 'nishi', meaning: 'west' },
    'ここ': { romaji: 'koko', meaning: 'here' },
    'そこ': { romaji: 'soko', meaning: 'there' },
    'あそこ': { romaji: 'asoko', meaning: 'over there' },
    'みぎ': { romaji: 'migi', meaning: 'right' },
    'ひだり': { romaji: 'hidari', meaning: 'left' },
    'うえ': { romaji: 'ue', meaning: 'above, up' },
    'した': { romaji: 'shita', meaning: 'below, down' },
    'まえ': { romaji: 'mae', meaning: 'front' },
    'うしろ': { romaji: 'ushiro', meaning: 'behind' },
    'むこう': { romaji: 'mukō', meaning: 'the other side, opposite side' },
    'ななめ': { romaji: 'naname', meaning: 'diagonal' },
    'てまえ': { romaji: 'temae', meaning: 'nearer, more in front' },
    'とおい': { romaji: 'tooi', meaning: 'far' },
    'ちかい': { romaji: 'chikai', meaning: 'near, close' },
    'ゆ': { romaji: 'yu', meaning: 'hot water' },
    'こおり': { romaji: 'kōri', meaning: 'ice' },
    'ゆげ': { romaji: 'yuge', meaning: 'steam' },
    'ひ': { romaji: 'hi', meaning: 'fire' },
    'ガス': { romaji: 'gasu', meaning: 'gas' },
    'くうき': { romaji: 'kūki', meaning: 'air, atmosphere' },
    'つち': { romaji: 'tsuchi', meaning: 'earth, ground' },
    'きんぞく': { romaji: 'kinzoku', meaning: 'metal, metallic' },
    'どろ': { romaji: 'doro', meaning: 'mud, mire, clay, plaster' },
    'けむり': { romaji: 'kemuri', meaning: 'smoke, tobacco, opium' },
    'てつ': { romaji: 'tetsu', meaning: 'iron [Fe]' },
    'どう': { romaji: 'dō', meaning: 'copper [Cu]' },
    'きん': { romaji: 'kin', meaning: 'gold [Au]; money' },
    'ぎん': { romaji: 'gin', meaning: 'silver [Ag]; wealth' },
    'なまり': { romaji: 'namari', meaning: 'lead [Pb]' },
    'メートル': { romaji: 'mētoru', meaning: 'meter' },
    'リットル': { romaji: 'rittoru', meaning: 'litre' },
    'グラム': { romaji: 'guramu', meaning: 'gram' },
    'キロ': { romaji: 'kiro', meaning: 'kilo-' },
    'ミリ': { romaji: 'miri', meaning: 'milli-' },
    'センチメートル': { romaji: 'senchi', meaning: 'centimeter' },
    'センチ': { romaji: 'senchi', meaning: 'centimeter' },
    'インチ': { romaji: 'inchi', meaning: 'inch' },
    'しゃかい': { romaji: 'shakai', meaning: 'society' },
    'けいざい': { romaji: 'keizai', meaning: 'economy, economics' },
    'かいしゃ': { romaji: 'kaisha', meaning: 'company' },
    'かいぎ': { romaji: 'kaigi', meaning: 'meeting' },
    'がっこう': { romaji: 'gakkō', meaning: 'school' },
    'やくしょ': { romaji: 'yakusho', meaning: 'local government office' },
    'みせ': { romaji: 'mise', meaning: 'store' },
    'ホテル': { romaji: 'hoteru', meaning: 'hotel' },
    'こうじょう': { romaji: 'kōjō', meaning: 'factory' },
    'かね': { romaji: 'kane', meaning: 'money' },
    'さつ': { romaji: 'satsu', meaning: 'bill [of money, e.g., a thousand-yen bill]' },
    'こぜに': { romaji: 'kozeni', meaning: 'small change' },
    'つりせん': { romaji: 'tsurisen', meaning: 'change' },
    'おつり': { romaji: 'o-tsuri', meaning: 'change' },
    'じどうはんばいき': { romaji: 'jidōhanbaiki', meaning: 'vending machine, slot machine' },
    'きっぷ': { romaji: 'kippu', meaning: 'ticket (public transport, fine)' },
    'きって': { romaji: 'kitte', meaning: 'stamp' },
    'つくえ': { romaji: 'tsukue', meaning: 'desk' },
    'いす': { romaji: 'isu', meaning: 'chair, position' },
    'たたみ': { romaji: 'tatami', meaning: 'a tatami mat' },
    'と': { romaji: 'to', meaning: 'door, family' },
    'とびら': { romaji: 'tobira', meaning: 'door panel' },
    'ドア': { romaji: 'doa', meaning: 'door' },
    'まど': { romaji: 'mado', meaning: 'window' },
    'ふとん': { romaji: 'futon', meaning: 'futon' },
    'げんかん': { romaji: 'genkan', meaning: 'entrance' },
    'いえ': { romaji: 'ie', meaning: 'house, home' },
    'エレベーター': { romaji: 'erebētā', meaning: 'elevator' },
    'エスカレーター': { romaji: 'esukarētā', meaning: 'escalator' },
    'でんき': { romaji: 'denki', meaning: 'electricity' },
    'くぎ': { romaji: 'kugi', meaning: 'nail, spike' },
    'ひも': { romaji: 'himo', meaning: 'string, cord' },
    'なわ': { romaji: 'nawa', meaning: 'rope, string' },
    'ふくろ': { romaji: 'fukuro', meaning: 'pocket, bag' },
    'かばん': { romaji: 'kaban', meaning: 'leather bag' },
    'かさ': { romaji: 'kasa', meaning: 'umbrella, parasol' },
    'かぎ': { romaji: 'kagi', meaning: 'door bolt, key' },
    'ちょうこく': { romaji: 'chōkoku', meaning: 'sculpture, engraving' },
    'ぶんぼうぐ': { romaji: 'bunbōgu', meaning: 'stationery' },
    'インク': { romaji: 'inku', meaning: 'ink' },
    'ペン': { romaji: 'pen', meaning: 'pen' },
    'ボールペン': { romaji: 'bōrupen', meaning: 'ball-point pen' },
    'まんねんひつ': { romaji: 'mannenhitsu', meaning: 'fountain pen' },
    'えんぴつ': { romaji: 'enpitsu', meaning: 'pencil' },
    'ふで': { romaji: 'fude', meaning: 'brush for writing or painting' },
    'チョーク': { romaji: 'chōku', meaning: 'chalk' },
    'けしゴム': { romaji: 'keshigomu', meaning: 'eraser' },
    'えんぴつけずり': { romaji: 'enpitsu-kezuri', meaning: 'pencil sharpener' },
    'じょうぎ': { romaji: 'jōgi', meaning: 'ruler' },
    'ノート': { romaji: 'nōto', meaning: 'notebook' },
    'にっき': { romaji: 'nikki', meaning: 'diary' },
    'カバー': { romaji: 'kabā', meaning: 'book cover' },
    'ふうとう': { romaji: 'fūtō', meaning: 'envelope' },
    'はさみ': { romaji: 'hasami', meaning: 'scissors' },
    'ホッチキス': { romaji: 'hotchikisu', meaning: 'stapler' },
    'ふく': { romaji: 'fuku', meaning: 'clothes' },
    'ようふく': { romaji: 'yōfuku', meaning: 'western clothing' },
    'きもの': { romaji: 'kimono', meaning: 'kimono' },
    'わふく': { romaji: 'wafuku', meaning: 'Japanese clothing' },
    'そで': { romaji: 'sode', meaning: 'sleeve' },
    'えり': { romaji: 'eri', meaning: 'lapel, collar' },
    'ボタン': { romaji: 'botan', meaning: 'button' },
    'チャック': { romaji: 'chakku', meaning: 'zipper, zipper fastener' },
    'ファスナー': { romaji: 'fasunā', meaning: 'zipper, zipper fastener' },
    'ジッパー': { romaji: 'jippā', meaning: 'zipper, zipper fastener' },
    'ベルト': { romaji: 'beruto', meaning: 'belt' },
    'くつ': { romaji: 'kutsu', meaning: 'shoe' },
    'くつした': { romaji: 'kutsushita', meaning: 'sock' },
    'めがね': { romaji: 'megane', meaning: 'glasses' },
    'てつどう': { romaji: 'tetsudō', meaning: 'railway' },
    'えき': { romaji: 'eki', meaning: 'station' },
    'ひこうき': { romaji: 'hikōki', meaning: 'airplane' },
    'くうこう': { romaji: 'kūkō', meaning: 'airport' },
    'ひこうじょう': { romaji: 'hikōjō', meaning: 'airport' },
    'みち': { romaji: 'michi', meaning: 'street, way, road' },
    'どうろ': { romaji: 'dōro', meaning: 'road' },
    'バスてい': { romaji: 'basutei', meaning: 'bus-stop' },
    'とおり': { romaji: 'tōri', meaning: 'avenue' },
    'でんしゃ': { romaji: 'densha', meaning: 'train' },
    'くるま': { romaji: 'kuruma', meaning: 'car' },
    'じどうしゃ': { romaji: 'jidōsha', meaning: 'car' },
    'じてんしゃ': { romaji: 'jitensha', meaning: 'bicycle' },
    'もじ': { romaji: 'moji', meaning: 'letter, character, script' },
    'じ': { romaji: 'ji', meaning: 'a letter, character' },
    'かんじ': { romaji: 'kanji', meaning: 'Chinese character' },
    'ひらがな': { romaji: 'hiragana', meaning: 'hiragana syllabary characters' },
    'カタカナ': { romaji: 'katakana', meaning: 'katakana syllabary characters' },
    'すうじ': { romaji: 'sūji', meaning: 'numbers' },
    'アルファベット': { romaji: 'arufabetto', meaning: 'alphabet' },
    'ローマじ': { romaji: 'rōmaji', meaning: 'Roman characters, Latin script' },
    'がいこくご': { romaji: 'gaikokugo', meaning: 'foreign language' },
    'にほんご': { romaji: 'nihongo', meaning: 'Japanese [language]' },
    'こくご': { romaji: 'kokugo', meaning: 'Japanese [language]' },
    'えいご': { romaji: 'eigo', meaning: 'English [language]' },
    'ちゅうごくご': { romaji: 'chūgokugo', meaning: 'Chinese [language]' },
    'どいつご': { romaji: 'doitsugo', meaning: 'German [language]' },
    'すぺいんご': { romaji: 'supeingo', meaning: 'Spanish [language]' },
    'ふらんすご': { romaji: 'furansugo', meaning: 'French [language]' },
    'ちょうせんご': { romaji: 'chōsengo', meaning: 'Korean [language]' },
    'かんこくご': { romaji: 'kankokugo', meaning: 'South Korean [language]' },
    'ほん': { romaji: 'hon', meaning: 'book' },
    'かみ': { romaji: 'kami', meaning: 'paper' },
    'てがみ': { romaji: 'tegami', meaning: 'letter' },
    'しんぶん': { romaji: 'shinbun', meaning: 'newspaper' },
    'じしょ': { romaji: 'jisho', meaning: 'dictionary' },
    'パソコン': { romaji: 'pasokon', meaning: 'personal computer' },
    'いろ': { romaji: 'iro', meaning: 'color' },
    'しきさい': { romaji: 'shikisai', meaning: 'color' },
    'あか': { romaji: 'aka', meaning: 'red' },
    'きいろ': { romaji: 'kiiro', meaning: 'yellow' },
    'みどり': { romaji: 'midori', meaning: 'green' },
    'あお': { romaji: 'ao', meaning: 'blue' },
    'むらさき': { romaji: 'murasaki', meaning: 'purple' },
    'むらさきいろ': { romaji: 'murasakiiro', meaning: 'purple' },
    'しろ': { romaji: 'shiro', meaning: 'white' },
    'くろ': { romaji: 'kuro', meaning: 'black' },
    'ピンク': { romaji: 'pinku', meaning: 'pink' },
    'ちゃいろ': { romaji: 'chairo', meaning: 'brown' },
    'はいいろ': { romaji: 'haiiro', meaning: 'grey' },
    'ねずみいろ': { romaji: 'nezumiiro', meaning: 'grey' },
    'オレンジ': { romaji: 'orenji', meaning: 'orange' },
    'え': { romaji: 'e', meaning: 'picture' },
    'おんがく': { romaji: 'ongaku', meaning: 'music' },
    'りか': { romaji: 'rika', meaning: 'science' },
    'さんすう': { romaji: 'sansū', meaning: 'arithmetic' },
    'れきし': { romaji: 'rekishi', meaning: 'history' },
    'ちり': { romaji: 'chiri', meaning: 'geography' },
    'たいいく': { romaji: 'taiiku', meaning: 'physical education' },
    'スポーツ': { romaji: 'supōtsu', meaning: 'sport' },
    'システム': { romaji: 'shisutemu', meaning: 'system' },
    'じょうほう': { romaji: 'jōhō', meaning: 'information, news' },
    'ひつよう': { romaji: 'hitsuyō', meaning: 'necessity' },
    'べんきょう': { romaji: 'benkyō', meaning: 'study' },
    'いらい': { romaji: 'irai', meaning: 'request' },
    'れい': { romaji: 'rei', meaning: 'zero' },
    'ゼロ': { romaji: 'zero', meaning: 'zero' },
    'いち': { romaji: 'ichi', meaning: 'one' },
    'に': { romaji: 'ni', meaning: 'two' },
    'さん': { romaji: 'san', meaning: 'three' },
    'よん': { romaji: 'yon', meaning: 'four' },
    'し': { romaji: 'shi', meaning: 'four' },
    'ご': { romaji: 'go', meaning: 'five' },
    'ろく': { romaji: 'roku', meaning: 'six' },
    'なな': { romaji: 'nana', meaning: 'seven' },
    'しち': { romaji: 'shichi', meaning: 'seven' },
    'はち': { romaji: 'hachi', meaning: 'eight' },
    'きゅう': { romaji: 'kyū', meaning: 'nine' },
    'く': { romaji: 'ku', meaning: 'nine' },
    'じゅう': { romaji: 'jū', meaning: 'ten' },
    'ひゃく': { romaji: 'hyaku', meaning: 'hundred' },
    'せん': { romaji: 'sen', meaning: 'thousand' },
    'まん': { romaji: 'man', meaning: 'ten thousand' },
    'おく': { romaji: 'oku', meaning: 'one hundred million' },
    'ひとつ': { romaji: 'hitotsu', meaning: 'one, one thing' },
    'ふたつ': { romaji: 'futatsu', meaning: 'two, two things' },
    'みっつ': { romaji: 'mittsu', meaning: 'three, three things' },
    'よっつ': { romaji: 'yottsu', meaning: 'four, four things' },
    'いつつ': { romaji: 'itsutsu', meaning: 'five, five things' },
    'むっつ': { romaji: 'muttsu', meaning: 'six, six things' },
    'ななつ': { romaji: 'nanatsu', meaning: 'seven, seven things' },
    'やっつ': { romaji: 'yattsu', meaning: 'eight, eight things' },
    'ここのつ': { romaji: 'kokonotsu', meaning: 'nine, nine things' },
    'とお': { romaji: 'tō', meaning: 'ten, ten things' },
    'これ': { romaji: 'kore', meaning: 'this, it' },
    'それ': { romaji: 'sore', meaning: 'that' },
    'あれ': { romaji: 'are', meaning: 'that over there' },
    'どれ': { romaji: 'dore', meaning: 'which' },
    'こちら': { romaji: 'kochira', meaning: 'this direction, thing, person, or place' },
    'こっち': { romaji: 'kocchi', meaning: 'this direction, thing, person, or place' },
    'そちら': { romaji: 'sochira', meaning: 'that direction, thing, person, or place' },
    'そっち': { romaji: 'socchi', meaning: 'that direction, thing, person, or place' },
    'あちら': { romaji: 'achira', meaning: 'that direction, thing, person, or place over there' },
    'あっち': { romaji: 'acchi', meaning: 'that direction, thing, person, or place over there' },
    'どちら': { romaji: 'dochira', meaning: 'which direction, thing, person, or place' },
    'どっち': { romaji: 'docchi', meaning: 'which direction, thing, person, or place' },
    'ひみつ': { romaji: 'himitsu', meaning: 'secret' },
    'じどう': { romaji: 'jidō', meaning: 'automatic' },
    'ないよう': { romaji: 'naiyō', meaning: 'content' },
    'はば': { romaji: 'haba', meaning: 'width, breadth, free room, difference (between two substances)' },
    'せいしき': { romaji: 'seishiki', meaning: 'formality' },
    'けっこん': { romaji: 'kekkon', meaning: 'marriage' },
    'げんざい': { romaji: 'genzai', meaning: 'now' },
    'いま': { romaji: 'ima', meaning: 'now' },
    'かこ': { romaji: 'kako', meaning: 'past' },
    'みらい': { romaji: 'mirai', meaning: 'future' },
    'いい': { romaji: 'ii', meaning: 'good' },
    'よい': { romaji: 'yoi', meaning: 'good' },
    'すごい': { romaji: 'sugoi', meaning: 'amazing' },
    'すばらしい': { romaji: 'subarashii', meaning: 'wonderful' },
    'わるい': { romaji: 'warui', meaning: 'bad, inferior' },
    'たかい': { romaji: 'takai', meaning: 'expensive, high' },
    'ひくい': { romaji: 'hikui', meaning: 'low' },
    'やすい': { romaji: 'yasui', meaning: 'cheap' },
    'おおきい': { romaji: 'ōkii', meaning: 'big' },
    'ちいさい': { romaji: 'chiisai', meaning: 'small' },
    'ほそい': { romaji: 'hosoi', meaning: 'thin' },
    'ふとい': { romaji: 'futoi', meaning: 'thick' },
    'ふるい': { romaji: 'furui', meaning: 'old' },
    'あたらしい': { romaji: 'atarashii', meaning: 'new' },
    'わかい': { romaji: 'wakai', meaning: 'young' },
    'かるい': { romaji: 'karui', meaning: 'light, easy' },
    'おもい': { romaji: 'omoi', meaning: 'heavy' },
    'やさしい': { romaji: 'yasashii', meaning: 'easy, simple' },
    'むずかしい': { romaji: 'muzukashii', meaning: 'difficult' },
    'やわらかい': { romaji: 'yawarakai', meaning: 'soft' },
    'かたい': { romaji: 'katai', meaning: 'hard' },
    'あつい': { romaji: 'atsui', meaning: 'hot' },
    'つめたい': { romaji: 'tsumetai', meaning: 'cold' },
    'さむい': { romaji: 'samui', meaning: 'cold (as in cold weather)' },
    'おいしい': { romaji: 'oishii', meaning: 'delicious' },
    'うまい': { romaji: 'umai', meaning: 'delicious, appetizing' },
    'まずい': { romaji: 'mazui', meaning: 'tastes awful' },
    'あまい': { romaji: 'amai', meaning: 'sweet' },
    'からい': { romaji: 'karai', meaning: 'hot [spicy]' },
    'しょっぱい': { romaji: 'shoppai', meaning: 'salty' },
    'にがい': { romaji: 'nigai', meaning: 'bitter' },
    'うつくしい': { romaji: 'utsukushii', meaning: 'beautiful' },
    'うれしい': { romaji: 'ureshii', meaning: 'happy' },
    'たのしい': { romaji: 'tanoshii', meaning: 'fun' },
    'かなしい': { romaji: 'kanashii', meaning: 'sad' },
    'さびしい': { romaji: 'sabishii', meaning: 'lonely' },
    'さみしい': { romaji: 'samishii', meaning: 'sad, lonely' },
    'こわい': { romaji: 'kowai', meaning: 'scary' },
    'いたい': { romaji: 'itai', meaning: 'painful' },
    'かゆい': { romaji: 'kayui', meaning: 'itchy' },
    'くさい': { romaji: 'kusai', meaning: 'stinky' },
    'つらい': { romaji: 'tsurai', meaning: 'painful, heart-breaking' },
    'する': { romaji: 'suru', meaning: 'to do' },
    'やる': { romaji: 'yaru', meaning: 'to do' },
    'いる': { romaji: 'iru', meaning: 'to exist [for animate objects]' },
    'ある': { romaji: 'aru', meaning: 'to exist [for inanimate objects]' },
    'なる': { romaji: 'naru', meaning: 'to become' },
    'おこる': { romaji: 'okoru', meaning: 'to occur' },
    'あらわれる': { romaji: 'arawareru', meaning: 'to appear' },
    'いきる': { romaji: 'ikiru', meaning: 'to live' },
    'うむ': { romaji: 'umu', meaning: 'to give birth' },
    'しぬ': { romaji: 'shinu', meaning: 'to die' },
    'こわれる': { romaji: 'kowareru', meaning: 'to breakin' },
    'いく': { romaji: 'iku', meaning: 'to go' },
    'くる': { romaji: 'kuru', meaning: 'to come' },
    'かえる': { romaji: 'kaeru', meaning: 'to return' },
    'あるく': { romaji: 'aruku', meaning: 'to walk' },
    'とぶ': { romaji: 'tobu', meaning: 'to jump, to fly' },
    'およぐ': { romaji: 'oyogu', meaning: 'to swim' },
    'うごく': { romaji: 'ugoku', meaning: 'to movein' },
    'おどる': { romaji: 'odoru', meaning: 'to dance' },
    'ねる': { romaji: 'neru', meaning: 'to sleep' },
    'うたう': { romaji: 'utau', meaning: 'to sing' },
    'かむ': { romaji: 'kamu', meaning: 'to bite' },
    'たべる': { romaji: 'taberu', meaning: 'to eat' },
    'のむ': { romaji: 'nomu', meaning: 'to drink' },
    'さわる': { romaji: 'sawaru', meaning: 'to touch' },
    'なげる': { romaji: 'nageru', meaning: 'to throw' },
    'もつ': { romaji: 'motsu', meaning: 'to hold' },
    'うつ': { romaji: 'utsu', meaning: 'to hit, to strike' },
    'なぐる': { romaji: 'naguru', meaning: 'to hit, to strike' },
    'さす': { romaji: 'sasu', meaning: 'to point' },
    'ける': { romaji: 'keru', meaning: 'to kick' },
    'すわる': { romaji: 'suwaru', meaning: 'to sit' },
    'たつ': { romaji: 'tatsu', meaning: 'to stand' },
    'はしる': { romaji: 'hashiru', meaning: 'to run' },
    'あく': { romaji: 'aku', meaning: 'to become unoccupied' },
    'こむ': { romaji: 'komu', meaning: 'to be crowded' },
    'かわく': { romaji: 'kawaku', meaning: 'to become dry' },
    'みだす': { romaji: 'midasu', meaning: 'to disturb, to disarrange' },
    'みだれる': { romaji: 'midareru', meaning: 'to be disturbed, to become confused' },
    'つかえる': { romaji: 'tsukaeru', meaning: 'to serve, to work for' },
    'そなわる': { romaji: 'sonawaru', meaning: 'to be furnished with' },
    'すぐれる': { romaji: 'sugureru', meaning: 'to excel, to surpass' },
    'ひえる': { romaji: 'hieru', meaning: 'to grow cold, to get chilly, to cool down' },
    'さめる': { romaji: 'sameru', meaning: 'to wake, to become sober, to be disillusioned' },
    'むく': { romaji: 'muku', meaning: 'to face, to turn toward' },
    'たおれる': { romaji: 'taoreru', meaning: 'to fall, to collapse' },
    'かたまる': { romaji: 'katamaru', meaning: 'to harden, to solidify, to become firm' },
    'うまる': { romaji: 'umaru', meaning: 'to be filled, to be surrounded, to overflow' },
    'うもれる': { romaji: 'umoreru', meaning: 'to be buried, to be covered' },
    'ます': { romaji: 'masu', meaning: 'to increase, to grow' },
    'ふえる': { romaji: 'fueru', meaning: 'to increase, to multiply' },
    'へる': { romaji: 'heru', meaning: 'to decrease' },
    'はずれる': { romaji: 'hazureru', meaning: 'to deviate' },
    'ふとる': { romaji: 'futoru', meaning: 'to grow fat' },
    'はじまる': { romaji: 'hajimaru', meaning: 'to begin' },
    'おわる': { romaji: 'owaru', meaning: 'to finish, to close' },
    'きめる': { romaji: 'kimeru', meaning: 'to decide' },
    'みる': { romaji: 'miru', meaning: 'to see' },
    'きく': { romaji: 'kiku', meaning: 'to hear, to listen' },
    'かぐ': { romaji: 'kagu', meaning: 'to smell' },
    'いう': { romaji: 'iu', meaning: 'to say' },
    'はなす': { romaji: 'hanasu', meaning: 'to speak' },
    'かたる': { romaji: 'kataru', meaning: 'to tell' },
    'かく': { romaji: 'kaku', meaning: 'to write' },
    'よむ': { romaji: 'yomu', meaning: 'to read' },
    'つかう': { romaji: 'tsukau', meaning: 'to use' },
    'つくる': { romaji: 'tsukuru', meaning: 'to make' },
    'なおす': { romaji: 'naosu', meaning: 'to fix, repair' },
    'すてる': { romaji: 'suteru', meaning: 'to discard, throw away' },
    'とる': { romaji: 'toru', meaning: 'to take' },
    'おく': { romaji: 'oku', meaning: 'to put' },
    'かなしむ': { romaji: 'kanashimu', meaning: 'to be sad' },
    'なく': { romaji: 'naku', meaning: 'to cry' },
    'わらう': { romaji: 'warau', meaning: 'to laugh' },
    'おこる': { romaji: 'okoru', meaning: 'to be angry' },
    'ほめる': { romaji: 'homeru', meaning: 'to encourage' },
    'しかる': { romaji: 'shikaru', meaning: 'to scold' },
    'よろこぶ': { romaji: 'yorokobu', meaning: 'to celebrate, to be jubilant, to have joy, to have delight, to have rapture' },
    'よろこび': { romaji: 'yorokobi', meaning: 'joy, delight, rapture' },
    'なぐさめる': { romaji: 'nagusameru', meaning: 'to console, to consolate, to provide empathy' },
    'あきる': { romaji: 'akiru', meaning: 'to be disinterested, to be bored, to be tired of, to be weary' },
    'おどろく': { romaji: 'odoroku', meaning: 'to be astonished, to be surprised, to be scared' },
    'あう': { romaji: 'au', meaning: 'to meet, to interview' },
    'あける': { romaji: 'akeru', meaning: 'to opentr, to unwraptr' },
    'あそぶ': { romaji: 'asobu', meaning: 'to play' },
    'あつまる': { romaji: 'atsumaru', meaning: 'to gatherin' },
    'うる': { romaji: 'uru', meaning: 'to sell' },
    'える': { romaji: 'eru', meaning: 'to obtain [some benefit or knowledge]' },
    'おる': { romaji: 'oru', meaning: 'to breaktr, to foldtr' },
    'かう': { romaji: 'kau', meaning: 'to buy' },
    'きる': { romaji: 'kiru', meaning: 'to cut' },
    'はく': { romaji: 'haku', meaning: 'to wear [on the lower body]' },
    'かえる': { romaji: 'kaeru', meaning: 'to changetr' },
    'しめる': { romaji: 'shimeru', meaning: 'to closetr' },
    'しる': { romaji: 'shiru', meaning: 'to know' },
    'つかれる': { romaji: 'tsukareru', meaning: 'to get tired' },
    'でかける': { romaji: 'dekakeru', meaning: 'to go out, to depart' },
    'はたらく': { romaji: 'hataraku', meaning: 'to work [e.g., at a job]' },
    'やすむ': { romaji: 'yasumu', meaning: 'to rest, to take a break, to go to bed' },
    'わかれる': { romaji: 'wakareru', meaning: 'to split intoin, to be divided' },
    'もう': { romaji: 'mō', meaning: 'already' },
    'まだ': { romaji: 'mada', meaning: 'still, yet' },
    'ずっと': { romaji: 'zutto', meaning: 'always' },
    'とても': { romaji: 'totemo', meaning: 'very' },
    'こう': { romaji: 'kō', meaning: 'like this' },
    'そう': { romaji: 'sō', meaning: 'like that' },
    'ああ': { romaji: 'ā', meaning: 'in that other way' },
    'どう': { romaji: 'dō', meaning: 'how' },
    'しばしば': { romaji: 'shibashiba', meaning: 'often' },
    'この': { romaji: 'kono', meaning: 'this' },
    'その': { romaji: 'sono', meaning: 'that' },
    'あの': { romaji: 'ano', meaning: 'that' },
    'どの': { romaji: 'dono', meaning: 'which' },
    'はい': { romaji: 'hai', meaning: 'yes' },
    'いいえ': { romaji: 'iie', meaning: 'no' },
    'でも': { romaji: 'demo', meaning: 'but' },
    'しかし': { romaji: 'shikashi', meaning: 'but, however' },
    'そして': { romaji: 'soshite', meaning: 'and then, Then…' },
    'それに': { romaji: 'soreni', meaning: 'besides' },
    'なぜなら': { romaji: 'nazenara', meaning: 'that is because, being because' },
    'う': { romaji: 'u', meaning: 'volitional ending [う for u-verbs, よう for ru-verbs]: "Let's…" or "I will"' },
    'よう': { romaji: 'yō', meaning: 'volitional ending [う for u-verbs, よう for ru-verbs]: "Let's…" or "I will"' },
    'せる': { romaji: 'seru', meaning: 'causative ending [せる for u-verbs, させる for ru-verbs]: to make [someone do something], to allow' },
    'させる': { romaji: 'saseru', meaning: 'causative ending [せる for u-verbs, させる for ru-verbs]: to make [someone do something], to allow' },
    'れる': { romaji: 'reru', meaning: 'passive verb ending [れる for u-verbs, られる for ru-verbs]: to be <verbed> [e.g., 食べられる, "to be eaten"]' },
    'られる': { romaji: 'rareru', meaning: 'passive verb ending [れる for u-verbs, られる for ru-verbs]: to be <verbed> [e.g., 食べられる, "to be eaten"]' },
    'そうだ': { romaji: 'sōda', meaning: 'indicates that it seems the verb occurs [e.g., "It seems he ate"]' },
    'た': { romaji: 'ta', meaning: 'informal past-tense' },
    'たい': { romaji: 'tai', meaning: 'indicates desire to perform verb' },
    'だろう': { romaji: 'darō', meaning: 'indicates that it seems the verb occurs; also used to ask whether the verb occurs' },
    'ない': { romaji: 'nai', meaning: 'informal negative' },
    'ん': { romaji: 'n', meaning: 'informal negative [ん is a slurred version and sounds a little masculine]' },
    'ぬ': { romaji: 'nu', meaning: 'archaic informal negative ["he hath", "thou didst", etc.]' },
    'ます': { romaji: 'masu', meaning: 'formal non-past ending' },
    'が': { romaji: 'ga', meaning: 'subject marker, but' },
    'で': { romaji: 'de', meaning: 'at, by' },
    'と': { romaji: 'to', meaning: 'and, with' },
    'に': { romaji: 'ni', meaning: 'indirect object marker' },
    'の': { romaji: 'no', meaning: 'possession marker, of' },
    'へ': { romaji: 'e', meaning: 'to' },
    'まで': { romaji: 'made', meaning: 'to' },
    'から': { romaji: 'kara', meaning: 'from' },
    'より': { romaji: 'yori', meaning: 'than' },
    'を': { romaji: 'o', meaning: 'direct object marker' },
    'および': { romaji: 'oyobi', meaning: 'and; as well as' },
    'か': { romaji: 'ka', meaning: 'whether' },
    'かも': { romaji: 'kamo', meaning: 'might be, possible that' },
    'それとも': { romaji: 'soretomo', meaning: 'or' },
    'だの': { romaji: 'dano', meaning: 'things like <list of things>, including, such things as' },
    'つつ': { romaji: 'tsutsu', meaning: 'ongoing occurrence [similar to ながら but has different tone, and both actions have equal weight]' },
    'て': { romaji: 'te', meaning: 'te form of verb or adjective' },
    'ながら': { romaji: 'nagara', meaning: 'while, though, both' },
    'ならびに': { romaji: 'narabini', meaning: 'as well as' },
    'なり': { romaji: 'nari', meaning: 'whether or not' },
    'ので': { romaji: 'node', meaning: 'so' },
    'また': { romaji: 'mata', meaning: 'also, again' },
    'または': { romaji: 'matawa', meaning: 'or alternatively' },
    'も': { romaji: 'mo', meaning: 'too, also' },
    'や': { romaji: 'ya', meaning: 'and' },
    'ね': { romaji: 'ne', meaning: 'emphasis and question marker, equivalent to "right?"' },
    'な': { romaji: 'na', meaning: 'the copula particle used after quasi-adjectives' },
    'かしら': { romaji: 'kashira', meaning: 'I wonder' },
    'さ': { romaji: 'sa', meaning: '-ness' },
    'っけ': { romaji: '-kke', meaning: 'particle indicating that the speaker is trying to recall some information ["What class is next -kke?"]' },
    'こそ': { romaji: 'koso', meaning: 'emphasis' },
    'さえ': { romaji: 'sae', meaning: 'even' },
    'しか': { romaji: 'shika', meaning: 'only' },
    'すら': { romaji: 'sura', meaning: 'even' },
    'くらい': { romaji: 'kurai', meaning: 'approximately, about' },
    'ぐらい': { romaji: 'guray', meaning: 'approximately, about' },
    'だけ': { romaji: 'dake', meaning: 'only, as much as' },
    'だって': { romaji: 'datte', meaning: 'however' },
    'ったら': { romaji: 'ttara', meaning: 'casual topic marker [colloquial form of to ittara (if you refer to ~; as for ~)' },
    'って': { romaji: 'tte', meaning: 'said that' },
    'どころ': { romaji: 'dokoro', meaning: '(particle used to indicate that what precedes it is an extreme example and strongly negates it)' },
    'など': { romaji: 'nado', meaning: 'for example' },
    'なら': { romaji: 'nara', meaning: 'if [for verbs]; subject marker [for nouns]' },
    'なんか': { romaji: 'nanka', meaning: 'casual undervalue, dislike, lack' },
    'なんて': { romaji: 'nante', meaning: 'casual undervalue, dislike, lack' },
    'は': { romaji: 'wa', meaning: 'topic marker' },
    'ばかり': { romaji: 'bakari', meaning: 'just, full of, only' },
    'ばっかり': { romaji: 'bakkari', meaning: 'just, full of, only' },
};

const kanji = {
    '一': { romaji: 'ichi', meaning: 'one' },
    '二': { romaji: 'ni', meaning: 'two' },
    '三': { romaji: 'san', meaning: 'three' },
    '四': { romaji: 'yon', meaning: 'four' },
    '五': { romaji: 'go', meaning: 'five' },
    '六': { romaji: 'roku', meaning: 'six' },
    '七': { romaji: 'shichi', meaning: 'seven' },
    '八': { romaji: 'hachi', meaning: 'eight' },
    '九': { romaji: 'kyuu', meaning: 'nine' },
    '十': { romaji: 'juu', meaning: 'ten' },
    '百': { romaji: 'hyaku', meaning: 'hundred' },
    '千': { romaji: 'sen', meaning: 'thousand' },
    '万': { romaji: 'ban', meaning: 'ten thousand' },
    '父': { romaji: 'fu', meaning: 'father' },
    '母': { romaji: 'bo', meaning: 'mother' },
    '友': { romaji: 'yuu', meaning: 'friend' },
    '女': { romaji: 'jo', meaning: 'woman' },
    '男': { romaji: 'dan', meaning: 'man' },
    '人': { romaji: 'jin', meaning: 'person' },
    '子': { romaji: 'shi', meaning: 'child' },
    '日': { romaji: 'jitsu', meaning: 'sun, day' },
    '月': { romaji: 'gatsu', meaning: 'month, moon' },
    '火': { romaji: 'ka', meaning: 'fire' },
    '水': { romaji: 'sui', meaning: 'water' },
    '木': { romaji: 'moku', meaning: 'tree, wood' },
    '金': { romaji: 'kin', meaning: 'gold, money' },
    '土': { romaji: 'do', meaning: 'earth, ground, soil' },
    '本': { romaji: 'hon', meaning: 'book, counter for long, slender objects' },
    '休': { romaji: 'kyuu', meaning: 'vacation, rest' },
    '語': { romaji: 'go', meaning: 'word, language, speech' },
    '年': { romaji: 'nen', meaning: 'year' },
    '午': { romaji: 'go', meaning: 'noon' },
    '前': { romaji: 'zen', meaning: 'before, in front of, previous' },
    '後': { romaji: 'go', meaning: 'behind, after' },
    '時': { romaji: 'ji', meaning: 'time' },
    '間': { romaji: 'kan', meaning: 'interval, space, room' },
    '毎': { romaji: 'mai', meaning: 'every' },
    '先': { romaji: 'sen', meaning: 'previous, ahead' },
    '今': { romaji: 'kon', meaning: 'now, present' },
    '何': { romaji: 'ka', meaning: 'what, how many' },
    '上': { romaji: 'jou', meaning: 'top, above, up' },
    '下': { romaji: 'ka', meaning: 'under, bottom, down' },
    '左': { romaji: 'sa', meaning: 'left' },
    '右': { romaji: 'yuu', meaning: 'right' },
    '東': { romaji: 'tou', meaning: 'east' },
    '西': { romaji: 'sei', meaning: 'west' },
    '南': { romaji: 'nan', meaning: 'south' },
    '北': { romaji: 'hoku', meaning: 'north' },
    '外': { romaji: 'gai', meaning: 'outside, foreign, other' },
    '名': { romaji: 'mei', meaning: 'name, famous, fame' },
    '高': { romaji: 'kou', meaning: 'high, expensive, tall' },
    '小': { romaji: 'shou', meaning: 'small, little' },
    '中': { romaji: 'chuu', meaning: 'middle, inside, center' },
    '大': { romaji: 'dai', meaning: 'big, large, great' },
    '長': { romaji: 'chou', meaning: 'leader, long' },
    '半': { romaji: 'han', meaning: 'half' },
    '分': { romaji: 'fun', meaning: 'understand, share, part' },
    '学': { romaji: 'gaku', meaning: 'learning, learn, science' },
    '校': { romaji: 'kou', meaning: 'school' },
    '生': { romaji: 'sei', meaning: 'live, birth, life' },
    '山': { romaji: 'san', meaning: 'mountain' },
    '川': { romaji: 'sen', meaning: 'river, stream' },
    '白': { romaji: 'haku', meaning: 'white' },
    '天': { romaji: 'ten', meaning: 'heaven, sky' },
    '雨': { romaji: 'u', meaning: 'rain' },
    '電': { romaji: 'den', meaning: 'electricity, electric, power' },
    '気': { romaji: 'ki', meaning: 'spirit, energy, power' },
    '車': { romaji: 'sha', meaning: 'car, vehicle, automobile' },
    '国': { romaji: 'koku', meaning: 'country, nation' },
    '円': { romaji: 'en', meaning: 'circle, yen, money' },
    '話': { romaji: 'wa', meaning: 'talk, topic, story' },
    '聞': { romaji: 'bun', meaning: 'hear, listen, ask' },
    '食': { romaji: 'shoku', meaning: 'eat, meal, food' },
    '読': { romaji: 'doku', meaning: 'read' },
    '来': { romaji: 'rai', meaning: 'come' },
    '書': { romaji: 'sho', meaning: 'book, document, papers' },
    '見': { romaji: 'ken', meaning: 'see, show' },
    '行': { romaji: 'gyou', meaning: 'go, leave' },
    '出': { romaji: 'shutsu', meaning: 'leave, go out' },
    '入': { romaji: 'nyuu', meaning: 'enter, insert, go in' },
    '会': { romaji: 'kai', meaning: 'meeting, meet' },
    '青': { romaji: 'sei', meaning: 'blue' },
    '赤': { romaji: 'seki', meaning: 'red' },
    '明': { romaji: 'mei', meaning: 'light, bright, dawn' },
    '秋': { romaji: 'shuu', meaning: 'fall, autumn' },
    '空': { romaji: 'kuu', meaning: 'sky, air, empty' },
    '開': { romaji: 'kai', meaning: 'open' },
    '悪': { romaji: 'aku', meaning: 'bad, evil' },
    '朝': { romaji: 'chou', meaning: 'morning' },
    '字': { romaji: 'ji', meaning: 'letter, character, mark' },
    '足': { romaji: 'ashi', meaning: 'foot, feet, sufficient' },
    '味': { romaji: 'mi', meaning: 'taste, experience' },
    '新': { romaji: 'shin', meaning: 'textframe, fresh' },
    '集': { romaji: 'shuu', meaning: 'collect, gather' },
    '兄': { romaji: 'kei', meaning: 'brother, older brother' },
    '姉': { romaji: 'shi', meaning: 'sister, older sister' },
    '歩': { romaji: 'ho', meaning: 'walk, step' },
    '有': { romaji: 'yuu', meaning: 'have, exist, be' },
    '安': { romaji: 'an', meaning: 'cheap, peaceful, safe' },
    '医': { romaji: 'i', meaning: 'heal, cure' },
    '意': { romaji: 'i', meaning: 'mind, heart, attention' },
    '以': { romaji: 'i', meaning: 'more, through, on account' },
    '言': { romaji: 'gen', meaning: 'speech, statement, word' },
    '家': { romaji: 'ka', meaning: 'house' },
    '急': { romaji: 'kyuu', meaning: 'hurry, quick' },
    '犬': { romaji: 'ken', meaning: 'dog' },
    '妹': { romaji: 'mai', meaning: 'sister, younger sister' },
    '色': { romaji: 'iro', meaning: 'color' },
    '音': { romaji: 'oto', meaning: 'sound' },
    '員': { romaji: 'in', meaning: 'member, official' },
    '院': { romaji: 'in', meaning: 'institution, academy' },
    '飲': { romaji: 'in', meaning: 'drink' },
    '魚': { romaji: 'sakana', meaning: 'fish' },
    '動': { romaji: 'ugoku', meaning: 'move' },
    '牛': { romaji: 'gyuu', meaning: 'cow, bull' },
    '歌': { romaji: 'ka', meaning: 'song, sing' },
    '写': { romaji: 'sha', meaning: 'copy, take a photo' },
    '映': { romaji: 'ei', meaning: 'reflect, project' },
    '海': { romaji: 'kai', meaning: 'sea, ocean' },
    '売': { romaji: 'bai', meaning: 'sale, sell' },
    '運': { romaji: 'un', meaning: 'luck, carry, move' },
    '重': { romaji: 'juu', meaning: 'heavy, important, stress' },
    '英': { romaji: 'ei', meaning: 'england, english, grand' },
    '駅': { romaji: 'eki', meaning: 'station (train) station' },
    '終': { romaji: 'shuu', meaning: 'end, finish, last' },
    '多': { romaji: 'ta', meaning: 'many, much, frequent' },
    '起': { romaji: 'ki', meaning: 'wake, get up, rise' },
    '屋': { romaji: 'oku', meaning: 'roof, house, shop' },
    '送': { romaji: 'sou', meaning: 'send' },
    '教': { romaji: 'kyou', meaning: 'teach, education, faith' },
    '弟': { romaji: 'dai', meaning: 'brother, younger brother' },
    '同': { romaji: 'dou', meaning: 'same, agree, equal' },
    '主': { romaji: 'shu', meaning: 'lord, master, principal' },
    '思': { romaji: 'shi', meaning: 'think, thought' },
    '親': { romaji: 'shin', meaning: 'parent, relative, familiar' },
    '花': { romaji: 'ka', meaning: 'flower' },
    '夏': { romaji: 'ka', meaning: 'summer' },
    '画': { romaji: 'ga', meaning: 'picture, stroke, stroke of kanji' },
    '界': { romaji: 'kai', meaning: 'world' },
    '買': { romaji: 'bai', meaning: 'buy' },
    '帰': { romaji: 'ki', meaning: 'return, arrive, come home' },
    '代': { romaji: 'dai', meaning: 'generation, substitute, exchange' },
    '楽': { romaji: 'gaku', meaning: 'music, comfort, ease' },
    '風': { romaji: 'fuu', meaning: 'wind, air, style' },
    '貸': { romaji: 'tai', meaning: 'lend' },
    '方': { romaji: 'hou', meaning: 'direction, way, person' },
    '紙': { romaji: 'shi', meaning: 'paper' },
    '通': { romaji: 'tsuu', meaning: 'avenue, traffic, go through' },
    '体': { romaji: 'tai', meaning: 'body, object' },
    '借': { romaji: 'shaku', meaning: 'borrow, rent' },
    '漢': { romaji: 'kan', meaning: 'china, chinese' },
    '館': { romaji: 'kan', meaning: 'building, palace' },
    '元': { romaji: 'gen', meaning: 'beginning, origin' },
    '考': { romaji: 'kou', meaning: 'think, consider, thought' },
    '着': { romaji: 'chaku', meaning: 'wear, wear clothes, arrive' },
    '究': { romaji: 'kyuu', meaning: 'research, study' },
    '去': { romaji: 'kyo', meaning: 'past, gone, leave' },
    '京': { romaji: 'kyou', meaning: 'capital' },
    '強': { romaji: 'kyou', meaning: 'strong, force' },
    '業': { romaji: 'gyou', meaning: 'business, vocation, job' },
    '切': { romaji: 'setsu', meaning: 'cut, cut off, slice' },
    '近': { romaji: 'kin', meaning: 'near, early, soon' },
    '銀': { romaji: 'gin', meaning: 'silver' },
    '口': { romaji: 'kou', meaning: 'mouth' },
    '工': { romaji: 'kou', meaning: 'construction, craft' },
    '黒': { romaji: 'koku', meaning: 'black' },
    '計': { romaji: 'kei', meaning: 'plan, measure' },
    '研': { romaji: 'ken', meaning: 'study, sharpen' },
    '建': { romaji: 'ken', meaning: 'build' },
    '験': { romaji: 'ken', meaning: 'test, examine, effect' },
    '古': { romaji: 'ko', meaning: 'old, old fashioned' },
    '広': { romaji: 'kou', meaning: 'wide, broad, big' },
    '心': { romaji: 'shin', meaning: 'heart, mind' },
    '試': { romaji: 'shi', meaning: 'test, try, experiment' },
    '答': { romaji: 'tou', meaning: 'solution, answer' },
    '事': { romaji: 'ji', meaning: 'thing, matter, business' },
    '転': { romaji: 'ten', meaning: 'revolve, turn, turn around' },
    '作': { romaji: 'saku', meaning: 'make, produce, prepare' },
    '茶': { romaji: 'cha', meaning: 'tea' },
    '早': { romaji: 'sou', meaning: 'fast, quick, early' },
    '止': { romaji: 'shi', meaning: 'stop' },
    '自': { romaji: 'ji', meaning: 'oneself, I, self' },
    '仕': { romaji: 'shi', meaning: 'official, serve, attend' },
    '死': { romaji: 'shi', meaning: 'death, die, dead' },
    '始': { romaji: 'shi', meaning: 'begin, beginning, start' },
    '使': { romaji: 'shi', meaning: 'use' },
    '私': { romaji: 'shi', meaning: 'I, me, private' },
    '地': { romaji: 'chi', meaning: 'ground, land, earth' },
    '持': { romaji: 'ji', meaning: 'have, hold, carry' },
    '質': { romaji: 'shitsu', meaning: 'quality, matter, substance' },
    '室': { romaji: 'shitsu', meaning: 'room, chamber' },
    '品': { romaji: 'hin', meaning: 'goods, article, dignity' },
    '社': { romaji: 'sha', meaning: 'company, firm, office' },
    '者': { romaji: 'sha', meaning: 'someone, person' },
    '手': { romaji: 'shu', meaning: 'hand' },
    '週': { romaji: 'shuu', meaning: 'week' },
    '習': { romaji: 'shuu', meaning: 'learn' },
    '住': { romaji: 'juu', meaning: 'live, reside, dwell' },
    '春': { romaji: 'shun', meaning: 'spring, spring (season)' },
    '正': { romaji: 'sei', meaning: 'correct, right, justice' },
    '少': { romaji: 'shou', meaning: 'few, little' },
    '場': { romaji: 'jou', meaning: 'area, location, place' },
    '知': { romaji: 'chi', meaning: 'know, wisdom' },
    '真': { romaji: 'shin', meaning: 'true, reality, truth' },
    '図': { romaji: 'zu', meaning: 'map, drawing, plan' },
    '世': { romaji: 'sei', meaning: 'world, society, generation' },
    '夕': { romaji: 'seki', meaning: 'evening' },
    '走': { romaji: 'sou', meaning: 'run' },
    '族': { romaji: 'zoku', meaning: 'tribe, family' },
    '注': { romaji: 'chuu', meaning: 'pour, flow, concentrate' },
    '田': { romaji: 'den', meaning: 'field, rice field, rice patty' },
    '台': { romaji: 'dai', meaning: 'stand, stage, pedestal' },
    '待': { romaji: 'tai', meaning: 'wait, depend on' },
    '題': { romaji: 'dai', meaning: 'topic, subject' },
    '度': { romaji: 'do', meaning: 'degree, time, times occurred' },
    '立': { romaji: 'ritsu', meaning: 'stand, stand up' },
    '旅': { romaji: 'ryo', meaning: 'trip, travel' },
    '力': { romaji: 'ryoku', meaning: 'power, strength, exertion' },
    '昼': { romaji: 'chuu', meaning: 'noon, daytime, day' },
    '町': { romaji: 'chou', meaning: 'town, village' },
    '鳥': { romaji: 'chou', meaning: 'bird' },
    '店': { romaji: 'ten', meaning: 'store, shop, problem' },
    '問': { romaji: 'mon', meaning: 'question, ask' },
    '冬': { romaji: 'tou', meaning: 'winter, winter (season), course' },
    '道': { romaji: 'dou', meaning: 'way, road' },
    '堂': { romaji: 'dou', meaning: 'hall' },
    '特': { romaji: 'toku', meaning: 'special' },
    '肉': { romaji: 'niku', meaning: 'meat' },
    '野': { romaji: 'ya', meaning: 'plains, field' },
    '発': { romaji: 'hatsu', meaning: 'depart, start, happen' },
    '飯': { romaji: 'han', meaning: 'meal, rice, cooked rice' },
    '病': { romaji: 'byou', meaning: 'ill, sick' },
    '不': { romaji: 'fu', meaning: 'non, negative, bad' },
    '服': { romaji: 'fuku', meaning: 'clothing, obey' },
    '物': { romaji: 'butsu', meaning: 'thing, matter, object' },
    '文': { romaji: 'bun', meaning: 'sentence, literature' },
    '別': { romaji: 'betsu', meaning: 'separate, another, specially' },
    '勉': { romaji: 'ben', meaning: 'exertion' },
    '目': { romaji: 'moku', meaning: 'eye' },
    '用': { romaji: 'you', meaning: 'use, service, business' },
    '夜': { romaji: 'ya', meaning: 'night, evening' },
    '曜': { romaji: 'you', meaning: 'weekday' },
    '洋': { romaji: 'you', meaning: 'west, western, ocean' },
    '理': { romaji: 'ri', meaning: 'logic, reason, truth' },
    '料': { romaji: 'ryou', meaning: 'fee, materials' },
    '相': { romaji: 'ai', meaning: 'mutual, appearance, minister (of state)' },
    '愛': { romaji: 'ai', meaning: 'love, affection' },
    '合': { romaji: 'au', meaning: 'together, fit, to be together' },
    '商': { romaji: 'akinau', meaning: 'sell, trade' },
    '浅': { romaji: 'asai', meaning: 'shallow, superficial' },
    '預': { romaji: 'azukaru', meaning: 'keep, charge, deposit' },
    '汗': { romaji: 'ase', meaning: 'sweat, perspiration' },
    '遊': { romaji: 'asobu', meaning: 'play, idle, playful' },
    '値': { romaji: 'atai', meaning: 'value, price, to value' },
    '与': { romaji: 'ataeru', meaning: 'give, award, assign' },
    '温': { romaji: 'atatakai', meaning: 'warm, temperature' },
    '暖': { romaji: 'atatakai', meaning: 'warm, cordial' },
    '頭': { romaji: 'atama', meaning: 'head, top' },
    '辺': { romaji: 'atari', meaning: 'vicinity, neighborhood' },
    '当': { romaji: 'ataru', meaning: 'hit, win, guess' },
    '圧': { romaji: 'atsu', meaning: 'pressure' },
    '暑': { romaji: 'atsui', meaning: 'heat, hot, summer heat' },
    '熱': { romaji: 'atsui', meaning: 'heat, hot, fever' },
    '厚': { romaji: 'atsui', meaning: 'thick' },
    '跡': { romaji: 'ato', meaning: 'trace, marks, remains' },
    '暴': { romaji: 'abaku', meaning: 'disclose, open, violent' },
    '浴': { romaji: 'abiru', meaning: 'bathe' },
    '危': { romaji: 'abunai', meaning: 'dangerous, unsafe, unsteady' },
    '油': { romaji: 'abura', meaning: 'oil' },
    '脂': { romaji: 'abura', meaning: 'fat' },
    '甘': { romaji: 'amai', meaning: 'sweet' },
    '余': { romaji: 'amasu', meaning: 'remain, remainder, to leave over' },
    '編': { romaji: 'amu', meaning: 'compile, knit' },
    '過': { romaji: 'ayamachi', meaning: 'fault, exceed, pass' },
    '誤': { romaji: 'ayamaru', meaning: 'mistake, fault' },
    '荒': { romaji: 'arai', meaning: 'violent, wild, rough' },
    '洗': { romaji: 'arau', meaning: 'wash' },
    '争': { romaji: 'arasou', meaning: 'struggle, quarrel, dispute' },
    '改': { romaji: 'aratameru', meaning: 'change, reform, reformed' },
    '表': { romaji: 'arawasu', meaning: 'show, list, schedule' },
    '現': { romaji: 'arawasu', meaning: 'actual, appear' },
    '著': { romaji: 'arawasu', meaning: 'author, writer, remarkable' },
    '在': { romaji: 'aru', meaning: 'exist, country, suburbs' },
    '暗': { romaji: 'an', meaning: 'dark' },
    '委': { romaji: 'i', meaning: 'commit, entrust' },
    '衣': { romaji: 'i', meaning: 'clothes, garments' },
    '囲': { romaji: 'i', meaning: 'enclose, surround' },
    '位': { romaji: 'i', meaning: 'rank, position, about' },
    '胃': { romaji: 'i', meaning: 'stomach' },
    '易': { romaji: 'i', meaning: 'easy' },
    '移': { romaji: 'i', meaning: 'transfer, infect, move' },
    '依': { romaji: 'i', meaning: 'depend, depend on' },
    '偉': { romaji: 'i', meaning: 'great, remarkable' },
    '違': { romaji: 'i', meaning: 'differ, wrong' },
    '怒': { romaji: 'ikaru', meaning: 'anger, get angry, angry' },
    '息': { romaji: 'iki', meaning: 'breath' },
    '域': { romaji: 'iki', meaning: 'boundary' },
    '勢': { romaji: 'ikioi', meaning: 'power' },
    '幾': { romaji: 'iku', meaning: 'how many, some' },
    '育': { romaji: 'iku', meaning: 'bring up, educate, grow' },
    '戦': { romaji: 'ikusa', meaning: 'war' },
    '池': { romaji: 'ike', meaning: 'pond' },
    '勇': { romaji: 'isamu', meaning: 'brave' },
    '石': { romaji: 'ishi', meaning: 'stone, rock' },
    '泉': { romaji: 'izumi', meaning: 'spring' },
    '忙': { romaji: 'isogashii', meaning: 'busy' },
    '板': { romaji: 'ita', meaning: 'board, plate' },
    '痛': { romaji: 'itai', meaning: 'pain, hurt' },
    '抱': { romaji: 'idaku', meaning: 'hug, hold' },
    '頂': { romaji: 'itadaki', meaning: 'summit, receive, summit (mountain)' },
    '市': { romaji: 'ichi', meaning: 'market, city' },
    '糸': { romaji: 'ito', meaning: 'thread' },
    '営': { romaji: 'itonamu', meaning: 'manage, barracks' },
    '否': { romaji: 'ina', meaning: 'no, denial' },
    '命': { romaji: 'inochi', meaning: 'life, order' },
    '祈': { romaji: 'inoru', meaning: 'pray, to pray, prayer' },
    '要': { romaji: 'iru', meaning: 'require, necessary' },
    '居': { romaji: 'iru', meaning: 'reside' },
    '岩': { romaji: 'iwa', meaning: 'rock, crag' },
    '祝': { romaji: 'iwau', meaning: 'celebrate' },
    '引': { romaji: 'in', meaning: 'draw, pull' },
    '印': { romaji: 'in', meaning: 'sign, mark' },
    '因': { romaji: 'in', meaning: 'cause' },
    '羽': { romaji: 'u', meaning: 'feather, wing' },
    '宇': { romaji: 'u', meaning: 'universe, eaves, house' },
    '初': { romaji: 'hatsu', meaning: 'first, beginning, begin' },
    '植': { romaji: 'ueru', meaning: 'plant, to plant, set up' },
    '伺': { romaji: 'ukagau', meaning: 'ask, visit, hear' },
    '浮': { romaji: 'ukabu', meaning: 'float, to float, come to mind' },
    '受': { romaji: 'ukaru', meaning: 'receive, popularity, receptacle' },
    '承': { romaji: 'uketamawaru', meaning: 'hear, agree' },
    '失': { romaji: 'ushinau', meaning: 'lose, slip' },
    '薄': { romaji: 'usui', meaning: 'thin, pale, weak' },
    '疑': { romaji: 'utagau', meaning: 'doubt, suspect, suspicion' },
    '内': { romaji: 'uchi', meaning: 'inside' },
    '打': { romaji: 'utsu', meaning: 'strick, hit, beat' },
    '美': { romaji: 'utsukushii', meaning: 'beautiful, beauty' },
    '器': { romaji: 'utsuwa', meaning: 'vessel, tool' },
    '腕': { romaji: 'ude', meaning: 'arm, talent, ability' },
    '産': { romaji: 'ubu', meaning: 'childbearing, product, birth' },
    '馬': { romaji: 'uma', meaning: 'horse' },
    '埋': { romaji: 'umaru', meaning: 'bury, fill, fill up' },
    '敬': { romaji: 'uyamau', meaning: 'respect' },
    '裏': { romaji: 'ura', meaning: 'opposite, back, reverse' },
    '占': { romaji: 'uranau', meaning: 'divination, to hold (a seat), occupy' },
    '得': { romaji: 'uru', meaning: 'acquire, gain' },
    '絵': { romaji: 'e', meaning: 'picture' },
    '回': { romaji: 'e', meaning: 'turn, to turn' },
    '泳': { romaji: 'ei', meaning: 'swim' },
    '栄': { romaji: 'ei', meaning: 'glory, flourish' },
    '永': { romaji: 'ei', meaning: 'eternal' },
    '鋭': { romaji: 'ei', meaning: 'sharp' },
    '役': { romaji: 'eki', meaning: 'office, duty, service' },
    '液': { romaji: 'eki', meaning: 'liquid' },
    '枝': { romaji: 'eda', meaning: 'branch, tree branch' },
    '越': { romaji: 'etsu', meaning: 'exceed, cross, move' },
    '笑': { romaji: 'emu', meaning: 'laugh, smile' },
    '選': { romaji: 'erabu', meaning: 'choose, choice' },
    '園': { romaji: 'en', meaning: 'garden' },
    '遠': { romaji: 'en', meaning: 'far' },
    '塩': { romaji: 'en', meaning: 'salt' },
    '演': { romaji: 'en', meaning: 'act, perform, put on a play' },
    '延': { romaji: 'en', meaning: 'postpone, extend' },
    '煙': { romaji: 'en', meaning: 'smoke, smokey' },
    '緒': { romaji: 'sho', meaning: 'cord, string (of a musical instrument), beginning (lineage)' },
    '汚': { romaji: 'o', meaning: 'soil, dirty, get dirty' },
    '和': { romaji: 'wa', meaning: 'peace, Japan, sum' },
    '老': { romaji: 'oiru', meaning: 'old' },
    '負': { romaji: 'ou', meaning: 'lose, defeated, to bear' },
    '追': { romaji: 'ou', meaning: 'chase' },
    '王': { romaji: 'ou', meaning: 'king' },
    '黄': { romaji: 'ou', meaning: 'yellow' },
    '央': { romaji: 'ou', meaning: 'center, middle' },
    '横': { romaji: 'ou', meaning: 'side, width, beside' },
    '欧': { romaji: 'ou', meaning: 'europe, european' },
    '押': { romaji: 'ou', meaning: 'push' },
    '奥': { romaji: 'ou', meaning: 'interior, depths, inner' },
    '犯': { romaji: 'okasu', meaning: 'violate, offense, to commit' },
    '拝': { romaji: 'ogamu', meaning: 'worship, humbly' },
    '補': { romaji: 'oginau', meaning: 'supply, supplement, compensate' },
    '置': { romaji: 'oku', meaning: 'place, put' },
    '億': { romaji: 'oku', meaning: 'hundred million, 100,000,000' },
    '遅': { romaji: 'okureru', meaning: 'slow, late' },
    '贈': { romaji: 'okuru', meaning: 'gift, present, to present' },
    '幼': { romaji: 'osanai', meaning: 'childish, young' },
    '治': { romaji: 'ji', meaning: 'rule, govern, cure' },
    '収': { romaji: 'shuu', meaning: 'obtain, to store, pay (taxes)' },
    '恐': { romaji: 'osoreru', meaning: 'fear, anxiety, fearful' },
    '落': { romaji: 'ochiru', meaning: 'fall, to fall, drop' },
    '夫': { romaji: 'otto', meaning: 'husband, man' },
    '訪': { romaji: 'otozureru', meaning: 'visit' },
    '踊': { romaji: 'odori', meaning: 'dance, to dance' },
    '各': { romaji: 'onoono', meaning: 'each, every' },
    '帯': { romaji: 'obi', meaning: 'belt, region, to wear' },
    '覚': { romaji: 'oboeru', meaning: 'remember, understand' },
    '面': { romaji: 'omo', meaning: 'face, surface, front' },
    '折': { romaji: 'ori', meaning: 'break, fold' },
    '降': { romaji: 'kou', meaning: 'fall, come down, get off' },
    '御': { romaji: 'on', meaning: 'honorific prefix' },
    '香': { romaji: 'ka', meaning: 'fragrance, smell' },
    '科': { romaji: 'ka', meaning: 'subject of study' },
    '化': { romaji: 'ka', meaning: 'change, change into' },
    '荷': { romaji: 'ka', meaning: 'load' },
    '加': { romaji: 'ka', meaning: 'add' },
    '果': { romaji: 'ka', meaning: 'fruit, end' },
    '貨': { romaji: 'ka', meaning: 'money, goods' },
    '課': { romaji: 'ka', meaning: 'section, lesson' },
    '可': { romaji: 'ka', meaning: 'possible, approve' },
    '河': { romaji: 'ka', meaning: 'river' },
    '菓': { romaji: 'ka', meaning: 'candy, confectionery' },
    '靴': { romaji: 'ka', meaning: 'shoes' },
    '貝': { romaji: 'kai', meaning: 'shell, shellfish' },
    '階': { romaji: 'kai', meaning: 'floor (of a building), rank' },
    '械': { romaji: 'kai', meaning: 'machine' },
    '快': { romaji: 'kai', meaning: 'pleasant' },
    '解': { romaji: 'kai', meaning: 'explanation, solve, dissolve' },
    '灰': { romaji: 'kai', meaning: 'ashes' },
    '介': { romaji: 'kai', meaning: 'mediate, aid, come between' },
    '皆': { romaji: 'kai', meaning: 'all, everyone, everything' },
    '害': { romaji: 'gai', meaning: 'harm, calamity' },
    '交': { romaji: 'kau', meaning: 'mix, be mixed, associate' },
    '返': { romaji: 'kaesu', meaning: 'return' },
    '省': { romaji: 'kaerimiru', meaning: 'government department, omit, reflect upon' },
    '変': { romaji: 'kaeru', meaning: 'change, abnormal, strange' },
    '替': { romaji: 'kaeru', meaning: 'replace' },
    '換': { romaji: 'kaeru', meaning: 'exchange' },
    '係': { romaji: 'kakari', meaning: 'connect, in charge' },
    '掛': { romaji: 'kakari', meaning: 'hang, catch, call' },
    '限': { romaji: 'kagiru', meaning: 'limit' },
    '欠': { romaji: 'kaku', meaning: 'lack' },
    '角': { romaji: 'kaku', meaning: 'angle, corner, horn' },
    '客': { romaji: 'kaku', meaning: 'guest, customer' },
    '格': { romaji: 'kaku', meaning: 'norm, status' },
    '確': { romaji: 'kaku', meaning: 'certain, make certain' },
    '革': { romaji: 'kaku', meaning: 'leather, reform' },
    '額': { romaji: 'gaku', meaning: 'amount, forehead' },
    '賢': { romaji: 'kashikoi', meaning: 'wise, clever, smart' },
    '数': { romaji: 'kazu', meaning: 'count, number' },
    '形': { romaji: 'kata', meaning: 'shape, form, type' },
    '型': { romaji: 'kata', meaning: 'type' },
    '片': { romaji: 'kata', meaning: 'fragment, onesided' },
    '肩': { romaji: 'kata', meaning: 'shoulder' },
    '固': { romaji: 'katai', meaning: 'solid, firm, hard' },
    '難': { romaji: 'katai', meaning: 'difficult, hard, disaster' },
    '硬': { romaji: 'katai', meaning: 'hard' },
    '堅': { romaji: 'katai', meaning: 'firm, hard' },
    '傾': { romaji: 'katamuku', meaning: 'incline, lean' },
    '勝': { romaji: 'katsu', meaning: 'win, excel' },
    '活': { romaji: 'katsu', meaning: 'active, live, activity' },
    '割': { romaji: 'katsu', meaning: 'divide' },
    '担': { romaji: 'katsugu', meaning: 'bear, undertake' },
    '門': { romaji: 'mon', meaning: 'gate' },
    '悲': { romaji: 'kanashii', meaning: 'sad' },
    '必': { romaji: 'kanarazu', meaning: 'without fail' },
    '彼': { romaji: 'kano', meaning: 'he, that' },
    '構': { romaji: 'kamau', meaning: 'structure, posture, construct' },
    '神': { romaji: 'kami', meaning: 'God, god, mind' },
    '髪': { romaji: 'kami', meaning: 'hair' },
    '辛': { romaji: 'karai', meaning: 'spicy, hot (food), hard' },
    '枯': { romaji: 'karasu', meaning: 'dry, wither, to dry' },
    '絡': { romaji: 'karamaru', meaning: 'entwine, to twine around' },
    '軽': { romaji: 'karui', meaning: 'light, light (weight)' },
    '皮': { romaji: 'kawa', meaning: 'skin' },
    '側': { romaji: 'kawa', meaning: 'side' },
    '乾': { romaji: 'kawakasu', meaning: 'dry' },
    '寒': { romaji: 'kan', meaning: 'cold' },
    '感': { romaji: 'kan', meaning: 'feeling, sense, feel' },
    '完': { romaji: 'kan', meaning: 'complete, perfect' },
    '官': { romaji: 'kan', meaning: 'government' },
    '管': { romaji: 'kan', meaning: 'pipe, control' },
    '関': { romaji: 'kan', meaning: 'concern, barrier' },
    '観': { romaji: 'kan', meaning: 'view' },
    '刊': { romaji: 'kan', meaning: 'publish' },
    '慣': { romaji: 'kan', meaning: 'habit, custom, get used to' },
    '干': { romaji: 'kan', meaning: 'dry' },
    '巻': { romaji: 'kan', meaning: 'roll up, volume, roll' },
    '簡': { romaji: 'kan', meaning: 'simple' },
    '缶': { romaji: 'kan', meaning: 'can, canned (food, drink)' },
    '患': { romaji: 'kan', meaning: 'sickness, sick' },
    '丸': { romaji: 'gan', meaning: 'round' },
    '岸': { romaji: 'gan', meaning: 'shore, seashore' },
    '願': { romaji: 'gan', meaning: 'wish, ask a favor, desire' },
    '含': { romaji: 'gan', meaning: 'contain, include' },
    '記': { romaji: 'ki', meaning: 'write down, record' },
    '期': { romaji: 'ki', meaning: 'term, expect' },
    '希': { romaji: 'ki', meaning: 'rare, aspire, desire' },
    '季': { romaji: 'ki', meaning: 'season, season (of the year)' },
    '喜': { romaji: 'ki', meaning: 'joy, happy' },
    '機': { romaji: 'ki', meaning: 'machine, occation' },
    '規': { romaji: 'ki', meaning: 'rule, regulation' },
    '寄': { romaji: 'ki', meaning: 'approach, gather, contribute' },
    '机': { romaji: 'ki', meaning: 'desk' },
    '議': { romaji: 'gi', meaning: 'discuss, debate' },
    '技': { romaji: 'gi', meaning: 'skill' },
    '消': { romaji: 'kieru', meaning: 'extinguish, put out, spend' },
    '利': { romaji: 'kiku', meaning: 'advantage, profit' },
    '効': { romaji: 'kiku', meaning: 'effect, efficancy' },
    '兆': { romaji: 'kizashi', meaning: 'trillion, sign, symptom' },
    '刻': { romaji: 'kizamu', meaning: 'engrave, carve' },
    '築': { romaji: 'kizuku', meaning: 'build, construct, construction' },
    '競': { romaji: 'kisou', meaning: 'compete (in a race)' },
    '喫': { romaji: 'kitsu', meaning: 'inhale, drink' },
    '詰': { romaji: 'kitsu', meaning: 'cram, shorten' },
    '決': { romaji: 'kimeru', meaning: 'decide, be decided' },
    '君': { romaji: 'kimi', meaning: 'you, ruler, added to names of boys' },
    '逆': { romaji: 'gyaku', meaning: 'reverse, opposite' },
    '級': { romaji: 'kyuu', meaning: 'grade, level' },
    '球': { romaji: 'kyuu', meaning: 'ball' },
    '求': { romaji: 'kyuu', meaning: 'seek, search' },
    '泣': { romaji: 'kyuu', meaning: 'cry' },
    '救': { romaji: 'kyuu', meaning: 'rescue, save' },
    '給': { romaji: 'kyuu', meaning: 'supply, pay' },
    '久': { romaji: 'kyuu', meaning: 'long time' },
    '旧': { romaji: 'kyuu', meaning: 'old, former' },
    '吸': { romaji: 'kyuu', meaning: 'suck, breathe in' },
    '許': { romaji: 'kyo', meaning: 'permit, pardon, forgive' },
    '漁': { romaji: 'gyo', meaning: 'fish' },
    '清': { romaji: 'kiyoi', meaning: 'clean, clear, pure' },
    '橋': { romaji: 'kyou', meaning: 'bridge' },
    '共': { romaji: 'kyou', meaning: 'together' },
    '協': { romaji: 'kyou', meaning: 'cooperate' },
    '経': { romaji: 'kyou', meaning: 'manage, passage, circles of longitude' },
    '境': { romaji: 'kyou', meaning: 'boundary, border line' },
    '供': { romaji: 'kyou', meaning: 'attendant, offer' },
    '胸': { romaji: 'kyou', meaning: 'chest, chest (body part)' },
    '叫': { romaji: 'kyou', meaning: 'shout' },
    '況': { romaji: 'kyou', meaning: 'condition, state of things' },
    '狭': { romaji: 'kyou', meaning: 'narrow' },
    '挟': { romaji: 'kyou', meaning: 'hold between, clasp' },
    '曲': { romaji: 'kyoku', meaning: 'music, song, curve' },
    '局': { romaji: 'kyoku', meaning: 'bureau, segment' },
    '極': { romaji: 'kyoku', meaning: 'extreme, poles (north or south)' },
    '玉': { romaji: 'gyoku', meaning: 'gem, jewel' },
    '際': { romaji: 'kiwa', meaning: 'verge, occation' },
    '均': { romaji: 'kin', meaning: 'even, level' },
    '禁': { romaji: 'kin', meaning: 'prohibit, not allowed' },
    '勤': { romaji: 'kin', meaning: 'service' },
    '区': { romaji: 'ku', meaning: 'district, ward' },
    '苦': { romaji: 'ku', meaning: 'suffering, bitter, painful' },
    '庫': { romaji: 'ku', meaning: 'storehouse, warehouse' },
    '紅': { romaji: 'ku', meaning: 'crimson' },
    '具': { romaji: 'gu', meaning: 'tool, utensil, ingredient' },
    '偶': { romaji: 'guu', meaning: 'chance, even numbers, by chance' },
    '隅': { romaji: 'guu', meaning: 'nook, corner' },
    '草': { romaji: 'kusa', meaning: 'grass' },
    '薬': { romaji: 'kusuri', meaning: 'medicine, drug' },
    '掘': { romaji: 'kutsu', meaning: 'dig' },
    '配': { romaji: 'kubaru', meaning: 'distribute, deliver' },
    '首': { romaji: 'kubi', meaning: 'head, neck' },
    '組': { romaji: 'kumi', meaning: 'organize, assemble' },
    '曇': { romaji: 'kumoru', meaning: 'cloudy' },
    '蔵': { romaji: 'kura', meaning: 'store, warehouse, own' },
    '暮': { romaji: 'kurasu', meaning: 'dusk, grow dark, live' },
    '比': { romaji: 'kuraberu', meaning: 'compare' },
    '訓': { romaji: 'kun', meaning: 'instruct' },
    '軍': { romaji: 'gun', meaning: 'army, military' },
    '群': { romaji: 'gun', meaning: 'group, crowd' },
    '毛': { romaji: 'ke', meaning: 'hair' },
    '景': { romaji: 'kei', meaning: 'scene' },
    '警': { romaji: 'kei', meaning: 'guard, warn' },
    '芸': { romaji: 'gei', meaning: 'art, skill' },
    '迎': { romaji: 'gei', meaning: 'meet, welcome' },
    '劇': { romaji: 'geki', meaning: 'drama' },
    '血': { romaji: 'ketsu', meaning: 'blood' },
    '結': { romaji: 'ketsu', meaning: 'tie, conclude' },
    '険': { romaji: 'kewashii', meaning: 'danger, steep' },
    '県': { romaji: 'ken', meaning: 'prefecture' },
    '件': { romaji: 'ken', meaning: 'matter' },
    '券': { romaji: 'ken', meaning: 'ticket, certificate, coupon' },
    '検': { romaji: 'ken', meaning: 'examine' },
    '権': { romaji: 'ken', meaning: 'right, power' },
    '軒': { romaji: 'ken', meaning: 'eaves' },
    '原': { romaji: 'gen', meaning: 'original, plain' },
    '減': { romaji: 'gen', meaning: 'decrease' },
    '粉': { romaji: 'ko', meaning: 'powder' },
    '戸': { romaji: 'ko', meaning: 'door' },
    '湖': { romaji: 'ko', meaning: 'lake' },
    '個': { romaji: 'ko', meaning: 'individual' },
    '呼': { romaji: 'ko', meaning: 'call' },
    '雇': { romaji: 'ko', meaning: 'employ, hire' },
    '互': { romaji: 'go', meaning: 'reciprocal, mutual, each other' },
    '恋': { romaji: 'koi', meaning: 'love' },
    '濃': { romaji: 'koi', meaning: 'thick' },
    '光': { romaji: 'kou', meaning: 'light' },
    '向': { romaji: 'kou', meaning: 'turn toward, turn' },
    '幸': { romaji: 'kou', meaning: 'happy, happiness' },
    '港': { romaji: 'kou', meaning: 'port, harbor' },
    '好': { romaji: 'kou', meaning: 'like, favorable' },
    '航': { romaji: 'kou', meaning: 'navigate' },
    '候': { romaji: 'kou', meaning: 'season, serve' },
    '耕': { romaji: 'kou', meaning: 'till, plow, cultivate' },
    '鉱': { romaji: 'kou', meaning: 'ore, mine' },
    '講': { romaji: 'kou', meaning: 'lecture' },
    '更': { romaji: 'kou', meaning: 'retextframe, change, reform' },
    '肯': { romaji: 'kou', meaning: 'assent, consent' },
    '郊': { romaji: 'kou', meaning: 'suburb' },
    '号': { romaji: 'gou', meaning: 'number, signal, sign' },
    '被': { romaji: 'koumuru', meaning: 'wear (hat), suffer (damage)' },
    '声': { romaji: 'koe', meaning: 'voice' },
    '超': { romaji: 'koeru', meaning: 'surpass, very, super' },
    '氷': { romaji: 'koori', meaning: 'ice' },
    '凍': { romaji: 'kooru', meaning: 'freeze' },
    '谷': { romaji: 'koku', meaning: 'valley' },
    '告': { romaji: 'koku', meaning: 'notify' },
    '腰': { romaji: 'koshi', meaning: 'waist, hip' },
    '骨': { romaji: 'kotsu', meaning: 'bone' },
    '断': { romaji: 'kotowaru', meaning: 'resolve, cut off' },
    '細': { romaji: 'komakai', meaning: 'small, slender, thin' },
    '困': { romaji: 'komaru', meaning: 'trouble, be in trouble' },
    '込': { romaji: 'komu', meaning: 'crowded, into' },
    '米': { romaji: 'kome', meaning: 'rice, america' },
    '殺': { romaji: 'korosu', meaning: 'kill' },
    '怖': { romaji: 'kowai', meaning: 'fear, fearful, scared' },
    '根': { romaji: 'kon', meaning: 'root' },
    '混': { romaji: 'kon', meaning: 'mix, blend, associate with' },
    '婚': { romaji: 'kon', meaning: 'marry, marriage' },
    '差': { romaji: 'sa', meaning: 'difference' },
    '査': { romaji: 'sa', meaning: 'look into, investigate' },
    '砂': { romaji: 'sa', meaning: 'sand' },
    '再': { romaji: 'sa', meaning: 'repeat, again, another time' },
    '座': { romaji: 'za', meaning: 'seat, sit down, constellation' },
    '才': { romaji: 'sai', meaning: 'talent, age' },
    '祭': { romaji: 'sai', meaning: 'festival' },
    '菜': { romaji: 'sai', meaning: 'vegetable' },
    '最': { romaji: 'sai', meaning: 'most' },
    '妻': { romaji: 'sai', meaning: 'wife' },
    '採': { romaji: 'sai', meaning: 'pick, gather' },
    '済': { romaji: 'sai', meaning: 'settle, relieve' },
    '歳': { romaji: 'sai', meaning: 'year, age, age suffix' },
    '財': { romaji: 'sai', meaning: 'wealth' },
    '材': { romaji: 'zai', meaning: 'timber, materials' },
    '罪': { romaji: 'zai', meaning: 'sin, crime' },
    '坂': { romaji: 'saka', meaning: 'slope' },
    '酒': { romaji: 'sake', meaning: 'sake, alcohol' },
    '探': { romaji: 'sagasu', meaning: 'probe, search' },
    '捜': { romaji: 'sagasu', meaning: 'look for, search' },
    '杯': { romaji: 'sakazuki', meaning: 'cup, counter for cups' },
    '咲': { romaji: 'saku', meaning: 'bloom, come out' },
    '昨': { romaji: 'saku', meaning: 'yesterday, last...' },
    '冊': { romaji: 'saku', meaning: 'card, volume, counter for books' },
    '支': { romaji: 'sasaeru', meaning: 'support, branch' },
    '刺': { romaji: 'sasaru', meaning: 'stab, stab (with a knife)' },
    '指': { romaji: 'sasu', meaning: 'point, finger' },
    '定': { romaji: 'sadaka', meaning: 'fix, decide, establish' },
    '札': { romaji: 'satsu', meaning: 'bill, paper money, tag' },
    '刷': { romaji: 'satsu', meaning: 'print' },
    '察': { romaji: 'satsu', meaning: 'inspect, guess' },
    '雑': { romaji: 'zatsu', meaning: 'mixed, rough' },
    '様': { romaji: 'sama', meaning: 'mode, formal title, Mr. / Mrs.' },
    '冷': { romaji: 'samasu', meaning: 'cold' },
    '皿': { romaji: 'sara', meaning: 'plate, dish' },
    '触': { romaji: 'sawaru', meaning: 'touch, feel' },
    '算': { romaji: 'san', meaning: 'calculate' },
    '参': { romaji: 'san', meaning: 'attend' },
    '散': { romaji: 'san', meaning: 'scatter' },
    '賛': { romaji: 'san', meaning: 'approve, praise' },
    '残': { romaji: 'zan', meaning: 'remain, ruthless' },
    '次': { romaji: 'shi', meaning: 'next' },
    '歯': { romaji: 'shi', meaning: 'tooth' },
    '史': { romaji: 'shi', meaning: 'history' },
    '示': { romaji: 'shi', meaning: 'show, to show' },
    '師': { romaji: 'shi', meaning: 'master, teacher' },
    '資': { romaji: 'shi', meaning: 'resource' },
    '詞': { romaji: 'shi', meaning: 'words' },
    '誌': { romaji: 'shi', meaning: 'magazine' },
    '路': { romaji: 'ji', meaning: 'road' },
    '耳': { romaji: 'ji', meaning: 'ear' },
    '寺': { romaji: 'ji', meaning: 'buddhist temple' },
    '児': { romaji: 'ji', meaning: 'child' },
    '辞': { romaji: 'ji', meaning: 'word, resign, retire' },
    '似': { romaji: 'ji', meaning: 'look like, resemble' },
    '除': { romaji: 'ji', meaning: 'remove' },
    '式': { romaji: 'shiki', meaning: 'ceremony, style' },
    '識': { romaji: 'shiki', meaning: 'know' },
    '直': { romaji: 'jiki', meaning: 'straight, fix' },
    '静': { romaji: 'shizuka', meaning: 'quiet' },
    '滴': { romaji: 'shizuku', meaning: 'drop, drop (of liquid), trickle' },
    '沈': { romaji: 'shizumu', meaning: 'sink, to sink' },
    '湿': { romaji: 'shimeru', meaning: 'damp' },
    '実': { romaji: 'jitsu', meaning: 'real, truth, fruit' },
    '島': { romaji: 'shima', meaning: 'island' },
    '閉': { romaji: 'shimeru', meaning: 'close' },
    '捨': { romaji: 'sha', meaning: 'throw away, discard' },
    '昔': { romaji: 'shaku', meaning: 'old, long ago, former' },
    '弱': { romaji: 'jaku', meaning: 'weak, weakness' },
    '若': { romaji: 'jaku', meaning: 'young' },
    '守': { romaji: 'shu', meaning: 'protect, obey, guard' },
    '取': { romaji: 'shu', meaning: 'take' },
    '種': { romaji: 'shu', meaning: 'seed, variety' },
    '州': { romaji: 'shuu', meaning: 'state' },
    '拾': { romaji: 'shuu', meaning: 'pick up' },
    '周': { romaji: 'shuu', meaning: 'around, surrounding area' },
    '船': { romaji: 'shuu', meaning: 'boat, small boat' },
    '柔': { romaji: 'juu', meaning: 'soft, soft (to the touch)' },
    '宿': { romaji: 'shuku', meaning: 'stay, lodge, inn' },
    '述': { romaji: 'jutsu', meaning: 'speak, state' },
    '術': { romaji: 'jutsu', meaning: 'art' },
    '順': { romaji: 'jun', meaning: 'order, turn, obey' },
    '準': { romaji: 'jun', meaning: 'standard, rule, semi' },
    '純': { romaji: 'jun', meaning: 'pure, purity' },
    '所': { romaji: 'sho', meaning: 'place, area' },
    '処': { romaji: 'sho', meaning: 'deal with, manage' },
    '署': { romaji: 'sho', meaning: 'government office' },
    '諸': { romaji: 'sho', meaning: 'many' },
    '助': { romaji: 'jo', meaning: 'help' },
    '章': { romaji: 'shou', meaning: 'chapter' },
    '焼': { romaji: 'shou', meaning: 'burn' },
    '象': { romaji: 'shou', meaning: 'image, elephant' },
    '照': { romaji: 'shou', meaning: 'illuminate' },
    '賞': { romaji: 'shou', meaning: 'prize, award' },
    '招': { romaji: 'shou', meaning: 'invite' },
    '性': { romaji: 'shou', meaning: 'nature, gender' },
    '将': { romaji: 'shou', meaning: 'general officer, general' },
    '装': { romaji: 'shou', meaning: 'dress, decoration, adorn' },
    '召': { romaji: 'shou', meaning: 'summon' },
    '床': { romaji: 'shou', meaning: 'floor' },
    '姓': { romaji: 'shou', meaning: 'surname, family name' },
    '昇': { romaji: 'shou', meaning: 'ascend, go up, rise' },
    '紹': { romaji: 'shou', meaning: 'intoduce' },
    '星': { romaji: 'shou', meaning: 'star' },
    '政': { romaji: 'shou', meaning: 'politics, rule' },
    '精': { romaji: 'shou', meaning: 'refine, essence' },
    '乗': { romaji: 'jou', meaning: 'ride, get on' },
    '状': { romaji: 'jou', meaning: 'form, letter' },
    '常': { romaji: 'jou', meaning: 'normal, regular' },
    '情': { romaji: 'jou', meaning: 'condition, emotion' },
    '城': { romaji: 'jou', meaning: 'castle' },
    '蒸': { romaji: 'jou', meaning: 'evaporate, steam' },
    '畳': { romaji: 'jou', meaning: 'tatami, fold up, fold' },
    '成': { romaji: 'jou', meaning: 'become, form, achieve' },
    '職': { romaji: 'shoku', meaning: 'employment, job' },
    '調': { romaji: 'shiraberu', meaning: 'look up, research, tone' },
    '退': { romaji: 'shirizoku', meaning: 'retreat' },
    '森': { romaji: 'shin', meaning: 'forest' },
    '申': { romaji: 'shin', meaning: 'report, call' },
    '身': { romaji: 'shin', meaning: 'body, self' },
    '深': { romaji: 'shin', meaning: 'deep' },
    '進': { romaji: 'shin', meaning: 'advance, move forward' },
    '臣': { romaji: 'shin', meaning: 'subject, retainer' },
    '信': { romaji: 'shin', meaning: 'believe, message' },
    '針': { romaji: 'shin', meaning: 'needle' },
    '伸': { romaji: 'shin', meaning: 'stretch' },
    '寝': { romaji: 'shin', meaning: 'sleep, go to sleep' },
    '震': { romaji: 'shin', meaning: 'shake, quake' },
    '吹': { romaji: 'sui', meaning: 'blow' },
    '末': { romaji: 'sue', meaning: 'last part, end' },
    '優': { romaji: 'sugureru', meaning: 'gentle, kind, nice' },
    '涼': { romaji: 'suzushii', meaning: 'cool, cool (temp)' },
    '炭': { romaji: 'sumi', meaning: 'coal, charcoal' },
    '速': { romaji: 'sumiyaka', meaning: 'fast, quick' },
    '背': { romaji: 'se', meaning: 'back, back (body part)' },
    '晴': { romaji: 'sei', meaning: 'fine weather, sunny' },
    '制': { romaji: 'sei', meaning: 'system, control' },
    '製': { romaji: 'sei', meaning: 'manufactured, made in' },
    '税': { romaji: 'zei', meaning: 'tax' },
    '説': { romaji: 'zei', meaning: 'explain' },
    '席': { romaji: 'seki', meaning: 'seat' },
    '積': { romaji: 'seki', meaning: 'accumulate' },
    '責': { romaji: 'seki', meaning: 'burden, blame' },
    '績': { romaji: 'seki', meaning: 'achievements' },
    '隻': { romaji: 'seki', meaning: 'one of a pair, counter for boats' },
    '籍': { romaji: 'seki', meaning: 'register' },
    '雪': { romaji: 'setsu', meaning: 'snow' },
    '設': { romaji: 'setsu', meaning: 'set up' },
    '接': { romaji: 'setsu', meaning: 'contact, touch' },
    '絶': { romaji: 'zetsu', meaning: 'die out, cut off' },
    '線': { romaji: 'sen', meaning: 'line' },
    '専': { romaji: 'sen', meaning: 'exclusive, sole' },
    '全': { romaji: 'zen', meaning: 'whole' },
    '然': { romaji: 'zen', meaning: 'yes, however, but' },
    '祖': { romaji: 'so', meaning: 'ancestor' },
    '想': { romaji: 'so', meaning: 'conceived, image, imagination' },
    '総': { romaji: 'sou', meaning: 'total, general' },
    '窓': { romaji: 'sou', meaning: 'window' },
    '層': { romaji: 'sou', meaning: 'stratum, layer' },
    '双': { romaji: 'sou', meaning: 'set of two, twin, double' },
    '掃': { romaji: 'sou', meaning: 'sweep' },
    '燥': { romaji: 'sou', meaning: 'dry up' },
    '造': { romaji: 'zou', meaning: 'make, create' },
    '増': { romaji: 'zou', meaning: 'increase' },
    '像': { romaji: 'zou', meaning: 'image' },
    '臓': { romaji: 'zou', meaning: 'internal organ' },
    '憎': { romaji: 'zou', meaning: 'hate, dislike' },
    '束': { romaji: 'soku', meaning: 'tie, bundle' },
    '則': { romaji: 'soku', meaning: 'rule, law, act on' },
    '測': { romaji: 'soku', meaning: 'measure' },
    '続': { romaji: 'zoku', meaning: 'continue' },
    '底': { romaji: 'soko', meaning: 'bottom' },
    '損': { romaji: 'sokonau', meaning: 'loss, damage' },
    '卒': { romaji: 'sotsu', meaning: 'graduate' },
    '率': { romaji: 'sotsu', meaning: 'rate, percentage, lead' },
    '備': { romaji: 'sonaeru', meaning: 'provide' },
    '反': { romaji: 'sorasu', meaning: 'counter, against' },
    '村': { romaji: 'son', meaning: 'village' },
    '孫': { romaji: 'son', meaning: 'grandchild' },
    '存': { romaji: 'son', meaning: 'exist' },
    '尊': { romaji: 'son', meaning: 'honor, respect' },
    '太': { romaji: 'ta', meaning: 'big, thick, become fat' },
    '袋': { romaji: 'tai', meaning: 'sack, bag' },
    '第': { romaji: 'dai', meaning: 'rank, no. ~' },
    '平': { romaji: 'taira', meaning: 'flat, calm' },
    '倒': { romaji: 'taosu', meaning: 'topple, fall over' },
    '宝': { romaji: 'takara', meaning: 'treasure' },
    '宅': { romaji: 'taku', meaning: 'house, home' },
    '濯': { romaji: 'taku', meaning: 'rinse' },
    '竹': { romaji: 'take', meaning: 'bamboo' },
    '達': { romaji: 'tatsu', meaning: 'attain, arrive, plural marker' },
    '例': { romaji: 'tatoeru', meaning: 'example' },
    '頼': { romaji: 'tanomu', meaning: 'rely on, ask' },
    '卵': { romaji: 'tamago', meaning: 'egg' },
    '民': { romaji: 'tami', meaning: 'people' },
    '便': { romaji: 'tayori', meaning: 'post, convenient' },
    '短': { romaji: 'tan', meaning: 'short' },
    '単': { romaji: 'tan', meaning: 'single' },
    '談': { romaji: 'dan', meaning: 'talk' },
    '段': { romaji: 'dan', meaning: 'step' },
    '乳': { romaji: 'chi', meaning: 'milk' },
    '恥': { romaji: 'chi', meaning: 'shy, shame' },
    '畜': { romaji: 'chiku', meaning: 'livestock' },
    '虫': { romaji: 'chuu', meaning: 'insect' },
    '柱': { romaji: 'chuu', meaning: 'pillar' },
    '仲': { romaji: 'chuu', meaning: 'intermediary' },
    '宙': { romaji: 'chuu', meaning: 'outer space, space' },
    '駐': { romaji: 'chuu', meaning: 'stationed' },
    '貯': { romaji: 'cho', meaning: 'lay up, store' },
    '庁': { romaji: 'chou', meaning: 'government agency' },
    '珍': { romaji: 'chin', meaning: 'rare' },
    '都': { romaji: 'shi', meaning: 'metropolis, city' },
    '費': { romaji: 'tsuieru', meaning: 'expense' },
    '捕': { romaji: 'tsukamaru', meaning: 'catch, arrest' },
    '疲': { romaji: 'tsukareru', meaning: 'tired' },
    '付': { romaji: 'tsuku', meaning: 'attach, add' },
    '突': { romaji: 'tsuku', meaning: 'dash, thrust' },
    '包': { romaji: 'tsutsumu', meaning: 'envelop, wrap' },
    '努': { romaji: 'tsutomeru', meaning: 'exert' },
    '務': { romaji: 'tsutomeru', meaning: 'duty' },
    '募': { romaji: 'tsunoru', meaning: 'raise' },
    '粒': { romaji: 'tsubu', meaning: 'grain' },
    '連': { romaji: 'tsuraneru', meaning: 'link, succession' },
    '庭': { romaji: 'tei', meaning: 'court, garden' },
    '低': { romaji: 'tei', meaning: 'low' },
    '停': { romaji: 'tei', meaning: 'stop, halt' },
    '程': { romaji: 'tei', meaning: 'extent, span, degree' },
    '泥': { romaji: 'tei', meaning: 'mud' },
    '的': { romaji: 'teki', meaning: 'mark, target, suffix for making adj' },
    '適': { romaji: 'teki', meaning: 'suitable' },
    '鉄': { romaji: 'tetsu', meaning: 'iron' },
    '点': { romaji: 'ten', meaning: 'point, mark, dot' },
    '殿': { romaji: 'ten', meaning: 'palace, lord' },
    '登': { romaji: 'to', meaning: 'climb' },
    '徒': { romaji: 'to', meaning: 'follower' },
    '途': { romaji: 'to', meaning: 'way' },
    '渡': { romaji: 'to', meaning: 'cross, go across' },
    '塗': { romaji: 'to', meaning: 'apply on a surface' },
    '投': { romaji: 'tou', meaning: 'throw' },
    '等': { romaji: 'tou', meaning: 'equal, class' },
    '湯': { romaji: 'tou', meaning: 'hot water' },
    '灯': { romaji: 'tou', meaning: 'lamp' },
    '党': { romaji: 'tou', meaning: 'party, sect, group' },
    '到': { romaji: 'tou', meaning: 'arrive' },
    '逃': { romaji: 'tou', meaning: 'escape' },
    '盗': { romaji: 'tou', meaning: 'steal' },
    '筒': { romaji: 'tou', meaning: 'tube' },
    '塔': { romaji: 'tou', meaning: 'tower' },
    '童': { romaji: 'dou', meaning: 'child' },
    '働': { romaji: 'tou', meaning: 'work' },
    '銅': { romaji: 'dou', meaning: 'copper, bronze' },
    '導': { romaji: 'dou', meaning: 'lead, guide' },
    '溶': { romaji: 'toku', meaning: 'dissolve, melt' },
    '毒': { romaji: 'doku', meaning: 'poison' },
    '独': { romaji: 'doku', meaning: 'alone' },
    '届': { romaji: 'todoku', meaning: 'deliver, reach' },
    '飛': { romaji: 'tobasu', meaning: 'fly' },
    '留': { romaji: 'tomeru', meaning: 'stay, keep' },
    '泊': { romaji: 'tomaru', meaning: 'stay overnight, stay' },
    '富': { romaji: 'fuu', meaning: 'rich' },
    '鈍': { romaji: 'don', meaning: 'dull' },
    '無': { romaji: 'nai', meaning: 'without, nothing' },
    '亡': { romaji: 'nai', meaning: 'decease, dead' },
    '流': { romaji: 'nagasu', meaning: 'flow, current' },
    '鳴': { romaji: 'naku', meaning: 'cry, sound (from a bird...)' },
    '波': { romaji: 'nami', meaning: 'wave' },
    '並': { romaji: 'nami', meaning: 'line up, line' },
    '涙': { romaji: 'namida', meaning: 'tear, teardrop' },
    '悩': { romaji: 'nayamasu', meaning: 'suffer, worry' },
    '軟': { romaji: 'nan', meaning: 'soft' },
    '任': { romaji: 'nin', meaning: 'office, entrust' },
    '認': { romaji: 'nin', meaning: 'recognize' },
    '抜': { romaji: 'nuku', meaning: 'pullout, stand out' },
    '布': { romaji: 'nuno', meaning: 'cloth' },
    '猫': { romaji: 'neko', meaning: 'cat' },
    '眠': { romaji: 'nemui', meaning: 'sleep' },
    '練': { romaji: 'neru', meaning: 'to train, training' },
    '念': { romaji: 'nen', meaning: 'thoughts, remembering' },
    '燃': { romaji: 'nen', meaning: 'burn' },
    '農': { romaji: 'nou', meaning: 'farming, farm' },
    '能': { romaji: 'nou', meaning: 'ability' },
    '脳': { romaji: 'nou', meaning: 'brain' },
    '望': { romaji: 'nozomu', meaning: 'hope, desire, expect' },
    '葉': { romaji: 'ha', meaning: 'leaf, leaves' },
    '破': { romaji: 'ha', meaning: 'tear, break' },
    '敗': { romaji: 'hai', meaning: 'defeated' },
    '倍': { romaji: 'bai', meaning: 'times X, double' },
    '量': { romaji: 'hakaru', meaning: 'quantity' },
    '麦': { romaji: 'baku', meaning: 'wheat' },
    '爆': { romaji: 'baku', meaning: 'explode' },
    '箱': { romaji: 'hako', meaning: 'box' },
    '畑': { romaji: 'hata', meaning: 'field' },
    '肌': { romaji: 'hada', meaning: 'skin' },
    '法': { romaji: 'hatsu', meaning: 'law' },
    '鼻': { romaji: 'hana', meaning: 'nose' },
    '放': { romaji: 'hanasu', meaning: 'let go, separate' },
    '幅': { romaji: 'haba', meaning: 'width' },
    '林': { romaji: 'hayashi', meaning: 'woods, forest' },
    '腹': { romaji: 'hara', meaning: 'belly, stomach' },
    '払': { romaji: 'harau', meaning: 'pay, clear away' },
    '判': { romaji: 'han', meaning: 'judge' },
    '版': { romaji: 'han', meaning: 'print, publishing' },
    '般': { romaji: 'han', meaning: 'sort, generally' },
    '販': { romaji: 'han', meaning: 'sell' },
    '番': { romaji: 'ban', meaning: 'order, turn, watch' },
    '晩': { romaji: 'ban', meaning: 'evening' },
    '非': { romaji: 'hi', meaning: 'not, not good' },
    '匹': { romaji: 'hiki', meaning: 'equal, counter for small animals' },
    '筆': { romaji: 'hitsu', meaning: 'brush, writing' },
    '兵': { romaji: 'hyou', meaning: 'soldier' },
    '秒': { romaji: 'byou', meaning: 'second' },
    '貧': { romaji: 'hin', meaning: 'poor, poverty' },
    '瓶': { romaji: 'bin', meaning: 'bottle, vase' },
    '府': { romaji: 'fu', meaning: 'prefecture, agency' },
    '婦': { romaji: 'fu', meaning: 'woman' },
    '符': { romaji: 'fu', meaning: 'symbol' },
    '普': { romaji: 'fu', meaning: 'wide, universal, general' },
    '膚': { romaji: 'fu', meaning: 'skin' },
    '部': { romaji: 'bu', meaning: 'department, section' },
    '武': { romaji: 'bu', meaning: 'military' },
    '舞': { romaji: 'bu', meaning: 'dance' },
    '封': { romaji: 'fuu', meaning: 'seal' },
    '福': { romaji: 'fuku', meaning: 'fortune' },
    '副': { romaji: 'fuku', meaning: 'secondary' },
    '復': { romaji: 'fuku', meaning: 'return, again, return to' },
    '複': { romaji: 'fuku', meaning: 'compound, complex' },
    '防': { romaji: 'fusegu', meaning: 'prevent' },
    '沸': { romaji: 'futsu', meaning: 'boil' },
    '仏': { romaji: 'butsu', meaning: 'buddha, france' },
    '報': { romaji: 'hou', meaning: 'inform, information' },
    '豊': { romaji: 'hou', meaning: 'plentiful, abundance' },
    '貿': { romaji: 'bou', meaning: 'trade' },
    '忘': { romaji: 'bou', meaning: 'forget' },
    '棒': { romaji: 'bou', meaning: 'stick, rod' },
    '坊': { romaji: 'bou', meaning: 'boy, priest' },
    '帽': { romaji: 'bou', meaning: 'headgear, headwear' },
    '欲': { romaji: 'hoshii', meaning: 'desire, want' },
    '磨': { romaji: 'ma', meaning: 'polish, brush (teeth)' },
    '枚': { romaji: 'mai', meaning: 'counter for sheets (paper)' },
    '迷': { romaji: 'mayou', meaning: 'perplexed, lost' },
    '満': { romaji: 'man', meaning: 'full' },
    '未': { romaji: 'mi', meaning: 'not yet, still to come' },
    '乱': { romaji: 'midasu', meaning: 'disordered' },
    '緑': { romaji: 'midori', meaning: 'green' },
    '夢': { romaji: 'mu', meaning: 'dream' },
    '娘': { romaji: 'musume', meaning: 'daughter, girl' },
    '綿': { romaji: 'men', meaning: 'cotton' },
    '戻': { romaji: 'modosu', meaning: 'return' },
    '約': { romaji: 'yaku', meaning: 'promise, contract' },
    '由': { romaji: 'yu', meaning: 'reason' },
    '輸': { romaji: 'yu', meaning: 'transport' },
    '郵': { romaji: 'yuu', meaning: 'mail' },
    '予': { romaji: 'yo', meaning: 'advance' },
    '良': { romaji: 'yoi', meaning: 'good' },
    '陽': { romaji: 'you', meaning: 'sun, positive' },
    '容': { romaji: 'you', meaning: 'appearance, container, contain' },
    '翌': { romaji: 'yoku', meaning: 'following, the next' },
    '礼': { romaji: 'rai', meaning: 'etiquette, bow, rite' },
    '陸': { romaji: 'riku', meaning: 'land' },
    '律': { romaji: 'richi', meaning: 'law, rhythm' },
    '略': { romaji: 'ryaku', meaning: 'abridged, strategy' },
    '両': { romaji: 'ryou', meaning: 'both' },
    '領': { romaji: 'ryou', meaning: 'territory' },
    '了': { romaji: 'ryou', meaning: 'finish, comprehend' },
    '療': { romaji: 'ryou', meaning: 'treat, treatment' },
    '輪': { romaji: 'rin', meaning: 'wheel, ring' },
    '類': { romaji: 'rui', meaning: 'kind, type' },
    '令': { romaji: 'rei', meaning: 'command' },
    '零': { romaji: 'rei', meaning: 'zero' },
    '齢': { romaji: 'rei', meaning: 'age' },
    '歴': { romaji: 'reki', meaning: 'personal history, history' },
    '列': { romaji: 'retsu', meaning: 'row, line' },
    '労': { romaji: 'rou', meaning: 'labor, effort' },
    '録': { romaji: 'roku', meaning: 'record' },
    '論': { romaji: 'ron', meaning: 'argue, theory' },
    '湾': { romaji: 'wan', meaning: 'bay' },
    '他': { romaji: 'ta', meaning: 'other, another' },
    '伝': { romaji: 'den', meaning: 'transmit, report, tradition' },
    '顔': { romaji: 'gan', meaning: 'face' },
    '団': { romaji: 'dan', meaning: 'group, association' },
    '対': { romaji: 'tai', meaning: 'opposite, versus, compare' },
    '舟': { romaji: 'shuu', meaning: 'boat, ship' },
    '雲': { romaji: 'wan', meaning: 'cloud' },
    '巨': { romaji: 'kyo', meaning: 'big, giant' },
};